"use client";

/** Demo-mode sample files, synthesised in the browser so users can try a tool
 *  instantly without uploading anything of their own. No assets to ship. */

export async function sampleImageFile(): Promise<File> {
  const canvas = document.createElement("canvas");
  canvas.width = 1600;
  canvas.height = 1000;
  const ctx = canvas.getContext("2d")!;
  const g = ctx.createLinearGradient(0, 0, 1600, 1000);
  g.addColorStop(0, "#4f46e5");
  g.addColorStop(0.5, "#0ea5e9");
  g.addColorStop(1, "#22d3ee");
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 1600, 1000);
  // decorative circles
  for (let i = 0; i < 18; i++) {
    ctx.beginPath();
    ctx.arc(Math.random() * 1600, Math.random() * 1000, Math.random() * 120 + 30, 0, Math.PI * 2);
    ctx.fillStyle = `rgba(255,255,255,${Math.random() * 0.15})`;
    ctx.fill();
  }
  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 96px system-ui, sans-serif";
  ctx.textAlign = "center";
  ctx.fillText("Sample Image", 800, 520);
  ctx.font = "40px system-ui, sans-serif";
  ctx.globalAlpha = 0.85;
  ctx.fillText("TechToolsCenter demo · 1600 × 1000", 800, 590);
  const blob = await new Promise<Blob | null>((res) => canvas.toBlob(res, "image/jpeg", 0.98));
  return new File([blob as Blob], "sample-image.jpg", { type: "image/jpeg" });
}

export async function samplePdfFile(): Promise<File> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  for (let p = 1; p <= 3; p++) {
    if (p > 1) doc.addPage();
    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, 210, 30, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text(`Sample PDF — page ${p}`, 14, 20);
    doc.setTextColor(40);
    doc.setFontSize(12);
    const lines = Array.from({ length: 25 }, (_, i) => `Line ${i + 1}: This is demo content generated by TechToolsCenter.`);
    doc.text(lines, 14, 45);
  }
  return new File([doc.output("blob")], "sample.pdf", { type: "application/pdf" });
}
