import type { Update } from "./types";

/**
 * Updates content collection. Append new entries here (or later load the same
 * shape from a CMS/JSON) — the pages render whatever sections are present, so
 * no layout changes are ever needed. Ordered newest-first by convention;
 * helpers still sort by date defensively.
 */
export const updates: Update[] = [
  /* ---------------- Platform / changelog (real) ---------------- */
  {
    slug: "india-hub-launch",
    title: "India Hub — official government service guides",
    category: "platform",
    summary: "A new first-class section with step-by-step guides to Aadhaar, PAN, passport, GST, certificates and more — with official links.",
    icon: "Landmark",
    publishedOn: "2026-07-18",
    readingMinutes: 2,
    tags: ["india hub", "launch", "government"],
    featured: true,
    popular: true,
    body: ["We launched India Hub — an educational directory that helps you navigate official Indian government services from one place, always linking out to the official website."],
    keyChanges: ["37+ service guides across 14 categories", "State and city-level pages", "Government schemes hub and a status-check hub", "A document finder and a personal 'My Documents' checklist"],
    relatedIndia: ["aadhaar-card", "pan-card", "passport"],
    relatedUpdates: ["hindi-guides", "schemes-hub", "status-hub"],
  },
  {
    slug: "hindi-guides",
    title: "Government service guides now in Hindi",
    category: "new-features",
    summary: "The most-searched India Hub guides are now available in Hindi, with an English ↔ हिंदी toggle on every page.",
    icon: "Languages",
    publishedOn: "2026-07-19",
    readingMinutes: 2,
    tags: ["hindi", "india hub", "accessibility"],
    featured: true,
    body: ["We added Hindi versions of the top government service guides so millions more users can follow the steps in their preferred language."],
    keyChanges: ["22 Hindi service guides", "English ↔ हिंदी toggle", "hreflang tags so Google indexes both languages"],
    howToUse: ["Open any supported service (e.g. Aadhaar, PAN, marriage certificate)", "Tap the 'हिंदी' toggle at the top", "Or open the Hindi hub at /hi/india-services"],
    relatedIndia: ["marriage-certificate", "ration-card"],
    relatedUpdates: ["india-hub-launch"],
  },
  {
    slug: "homepage-daily-inspiration",
    title: "Homepage refresh — Daily Inspiration & Today's Challenge",
    category: "new-features",
    summary: "The homepage now features a daily quote, a productivity tip, a rotating challenge and quick actions — a reason to come back every day.",
    icon: "Sparkles",
    publishedOn: "2026-07-20",
    readingMinutes: 2,
    tags: ["homepage", "daily", "productivity"],
    popular: true,
    body: ["We made the homepage feel alive and updated daily, while keeping the existing clean design."],
    keyChanges: ["Daily Inspiration card with a shareable quote of the day", "Today's Challenge that links to the right tool", "Quick actions and a 'This Week' snapshot"],
    howToUse: ["Open the homepage", "Read the quote of the day and tap Share to send it to WhatsApp or your status", "Try Today's Challenge in one tap"],
    relatedUpdates: ["india-hub-launch"],
  },
  {
    slug: "schemes-hub",
    title: "Government Schemes hub (Sarkari Yojana list)",
    category: "new-features",
    summary: "A filterable list of major government schemes — Ujjwala, PM Awas, Mudra, Atal Pension, Ayushman and more — grouped by who they help.",
    icon: "Award",
    publishedOn: "2026-07-19",
    readingMinutes: 1,
    tags: ["schemes", "yojana", "india hub"],
    keyChanges: ["17 scheme guides with benefits, eligibility and how to apply", "Filter by audience: women, farmers, students, seniors, business and more"],
    relatedIndia: ["jan-dhan-yojana", "pm-kisan"],
    relatedUpdates: ["india-hub-launch", "status-hub"],
  },
  {
    slug: "status-hub",
    title: "Check Status hub for common applications",
    category: "new-features",
    summary: "Track PAN, passport, PF, PM-KISAN, ration card, challan and more — each with the official tracker link and simple steps.",
    icon: "Search",
    publishedOn: "2026-07-19",
    readingMinutes: 1,
    tags: ["status", "tracking", "india hub"],
    keyChanges: ["12 status checks with official tracker links", "A phishing-safety note on every entry"],
    relatedIndia: ["pan-card", "passport"],
    relatedUpdates: ["schemes-hub"],
  },
  {
    slug: "editorial-policy-trust",
    title: "Editorial policy and verified sources on every guide",
    category: "security",
    summary: "Each India Hub guide now shows a 'Last updated' date and the official source it was verified against, plus a clear editorial policy.",
    icon: "ShieldCheck",
    publishedOn: "2026-07-20",
    readingMinutes: 1,
    tags: ["trust", "transparency", "e-e-a-t"],
    body: ["We added clear trust signals so you always know how current a guide is and where the information comes from."],
    keyChanges: ["'Last updated' date on every guide", "'Verified against' the official source", "A public editorial & research policy"],
    resources: [{ label: "Editorial policy", url: "/editorial-policy" }],
  },

  /* ---------------- Tool improvements (real) ---------------- */
  {
    slug: "pdf-compress-target-size",
    title: "PDF Compressor — target-size mode",
    category: "tool-improvements",
    summary: "Compress a PDF to an exact target size (e.g. under 200 KB) instead of guessing quality levels.",
    icon: "FileArchive",
    publishedOn: "2026-07-15",
    readingMinutes: 1,
    tags: ["pdf", "compression"],
    before: "You picked a quality level and hoped the file landed under the size limit.",
    after: "You enter a target size and the tool compresses until the PDF fits.",
    benefits: ["Hit portal upload limits on the first try", "No trial and error", "Still 100% in your browser"],
    relatedTools: ["pdf-compress", "compress-pdf-for-email"],
  },
  {
    slug: "image-compressor-presets",
    title: "Image Compressor — government upload presets",
    category: "tool-improvements",
    summary: "One-tap presets for common government forms so photos and scans meet size limits instantly.",
    icon: "ImageDown",
    publishedOn: "2026-07-16",
    readingMinutes: 1,
    tags: ["image", "compression", "government"],
    before: "You manually adjusted quality to get under 20–100 KB.",
    after: "Pick a preset (Aadhaar, PAN, passport photo, forms) and it's done.",
    benefits: ["Faster uploads", "Fewer rejected documents", "Works offline in your browser"],
    relatedTools: ["image-compressor", "image-compressor-for-passport-photo"],
    relatedIndia: ["aadhaar-card", "pan-card"],
  },

  /* ---------------- Google updates (evergreen explainers) ---------------- */
  {
    slug: "google-helpful-content-explained",
    title: "Google Helpful Content: what it means for you",
    category: "google",
    summary: "Google rewards content written to genuinely help people. Here's what that means and how it affects the sites you read.",
    icon: "Globe",
    publishedOn: "2026-07-10",
    readingMinutes: 3,
    tags: ["google", "seo", "helpful content"],
    popular: true,
    body: ["Google's 'helpful content' approach favours pages created primarily for people, not just to rank in search."],
    whyItMatters: "It pushes the web toward genuinely useful, trustworthy content — which is exactly how we write our guides.",
    whoIsAffected: "Anyone who searches on Google, and website owners who publish content.",
    keyChanges: ["Priority to people-first, experience-backed content", "Less visibility for thin, purely SEO-driven pages", "Emphasis on expertise, sourcing and trust (E-E-A-T)"],
    resources: [{ label: "Google Search Central", url: "https://developers.google.com/search" }],
    relatedBlog: [],
  },
  {
    slug: "google-core-updates-explained",
    title: "Google Core Updates, explained simply",
    category: "google",
    summary: "Every few months Google makes broad ranking changes. Here's what a core update is and why rankings move.",
    icon: "Globe",
    publishedOn: "2026-07-08",
    readingMinutes: 3,
    tags: ["google", "core update", "seo"],
    body: ["A core update is a broad improvement to how Google assesses content overall — not a penalty against any single site."],
    whyItMatters: "Rankings can shift after a core update; the fix is almost always to keep improving content quality, not chase tricks.",
    whoIsAffected: "Website owners and content creators; indirectly, everyone who searches.",
    keyChanges: ["Broad re-assessment of content quality", "No single 'thing to fix' — focus on overall helpfulness", "Recovery comes with sustained quality improvements"],
    resources: [{ label: "Google Search Status", url: "https://status.search.google.com" }],
  },
  {
    slug: "search-console-basics",
    title: "Google Search Console basics for any site owner",
    category: "google",
    summary: "Search Console shows how your site performs on Google. Here's what to set up first.",
    icon: "Gauge",
    publishedOn: "2026-07-05",
    readingMinutes: 3,
    tags: ["google", "search console", "seo"],
    body: ["Google Search Console is a free tool that shows your impressions, clicks and indexing status."],
    keyChanges: ["Verify your site", "Submit your XML sitemap", "Watch the Performance and Pages reports"],
    nextSteps: ["Add your property at search.google.com/search-console", "Submit sitemap.xml", "Review indexed pages weekly"],
    resources: [{ label: "Search Console", url: "https://search.google.com/search-console" }],
  },

  /* ---------------- Government notifications (evergreen) ---------------- */
  {
    slug: "pan-aadhaar-linking-notice",
    title: "PAN–Aadhaar linking: what you should know",
    category: "government",
    summary: "Most taxpayers must link PAN with Aadhaar. An unlinked PAN can become inoperative — here's how to check and fix it.",
    icon: "Landmark",
    publishedOn: "2026-07-12",
    readingMinutes: 2,
    tags: ["pan", "aadhaar", "income tax"],
    popular: true,
    whyItMatters: "An inoperative PAN can block ITR filing, refunds and many high-value financial transactions.",
    whoIsAffected: "PAN holders required to link under the Income Tax rules (with limited exemptions).",
    nextSteps: ["Check the link status on the Income Tax portal", "Pay any applicable late fee, then submit the link request", "Confirm with 'Link Aadhaar Status'"],
    officialSource: { label: "Income Tax e-filing portal", url: "https://www.incometax.gov.in" },
    relatedIndia: ["pan-aadhaar-link", "pan-card", "aadhaar-card"],
  },
  {
    slug: "aadhaar-keep-mobile-updated",
    title: "Keep your Aadhaar mobile number updated",
    category: "government",
    summary: "Many Aadhaar and DBT services rely on OTP to your registered mobile. Keeping it current avoids failed verifications.",
    icon: "Landmark",
    publishedOn: "2026-07-11",
    readingMinutes: 2,
    tags: ["aadhaar", "uidai", "otp"],
    whyItMatters: "OTP-based verification is used across banking, subsidies and government portals; an outdated number causes failures.",
    whoIsAffected: "Anyone whose Aadhaar mobile number has changed.",
    nextSteps: ["Visit an Aadhaar Seva Kendra to update your mobile", "Track the request with your URN"],
    officialSource: { label: "UIDAI", url: "https://uidai.gov.in" },
    relatedIndia: ["aadhaar-card"],
  },

  /* ---------------- Announcements / new features ---------------- */
  {
    slug: "my-documents-checklist",
    title: "New: 'My Documents' personal checklist",
    category: "new-features",
    summary: "Save any government service and tick off the documents you've collected — stored privately in your browser, no login.",
    icon: "FolderCheck",
    publishedOn: "2026-07-20",
    readingMinutes: 1,
    tags: ["india hub", "checklist", "productivity"],
    body: ["Track what you need for each application in one place."],
    howToUse: ["Open any India Hub service", "Tap 'Save to My Documents'", "Visit My Documents to tick off collected documents"],
    relatedIndia: ["passport", "marriage-certificate"],
    relatedUpdates: ["india-hub-launch"],
  },
  {
    slug: "pwa-install-offline",
    title: "Install TechToolsCenter as an app (PWA)",
    category: "new-features",
    summary: "Add TechToolsCenter to your home screen for an app-like experience, with core tools available even on a flaky connection.",
    icon: "Smartphone",
    publishedOn: "2026-07-02",
    readingMinutes: 1,
    tags: ["pwa", "offline", "mobile"],
    body: ["TechToolsCenter is a Progressive Web App — install it once and launch it like a native app."],
    howToUse: ["Open the site in your browser", "Choose 'Add to Home Screen' / 'Install'", "Launch it from your home screen anytime"],
    benefits: ["App-like, full-screen experience", "Fast repeat visits", "Client-side tools keep working offline"],
  },
];
