import type { DevResource } from "./types";

/**
 * TechToolsCenter's own tools, listed as the "Browser Tools" category so
 * developers never get sent to an external site for something we already
 * have built in.
 */
export const builtinDevTools: DevResource[] = [
  {
    slug: "builtin-json-formatter",
    name: "JSON Formatter",
    category: "browser-tools",
    description: "Beautify, minify and validate JSON with clear error messages — built into TechToolsCenter.",
    officialUrl: "/tools/json-formatter",
    tags: ["json", "formatter", "validator"],
    pricing: "Free",
    internalToolSlug: "json-formatter",
    icon: "Braces",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-base64",
    name: "Base64 Encode/Decode",
    category: "browser-tools",
    description: "Encode or decode Base64 text and files instantly in your browser.",
    officialUrl: "/tools/base64-encoder",
    tags: ["base64", "encode", "decode"],
    pricing: "Free",
    internalToolSlug: "base64-encoder",
    icon: "Binary",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-jwt-decoder",
    name: "JWT Decoder",
    category: "browser-tools",
    description: "Decode a JSON Web Token's header and payload to inspect its claims.",
    officialUrl: "/tools/jwt-decoder",
    tags: ["jwt", "auth", "decoder"],
    pricing: "Free",
    internalToolSlug: "jwt-decoder",
    icon: "KeyRound",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-hash-generator",
    name: "Hash Generator",
    category: "browser-tools",
    description: "Generate MD5, SHA-1, SHA-256 and other hashes from text or files.",
    officialUrl: "/tools/hash-generator",
    tags: ["hash", "sha256", "checksum"],
    pricing: "Free",
    internalToolSlug: "hash-generator",
    icon: "Hash",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-uuid-generator",
    name: "UUID Generator",
    category: "browser-tools",
    description: "Generate v4 UUIDs individually or in bulk for test data and IDs.",
    officialUrl: "/tools/uuid-generator",
    tags: ["uuid", "guid", "generator"],
    pricing: "Free",
    internalToolSlug: "uuid-generator",
    icon: "Fingerprint",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-qr-generator",
    name: "QR Code Generator",
    category: "browser-tools",
    description: "Create styled, branded QR codes for URLs, Wi-Fi, vCard, UPI and more.",
    officialUrl: "/tools/qr-generator",
    tags: ["qr code", "generator"],
    pricing: "Free",
    internalToolSlug: "qr-generator",
    icon: "ScanLine",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-qr-scanner",
    name: "QR Code Scanner",
    category: "browser-tools",
    description: "Scan a QR code with your camera or an uploaded image, right in the browser.",
    officialUrl: "/tools/qr-scanner",
    tags: ["qr code", "scanner", "camera"],
    pricing: "Free",
    internalToolSlug: "qr-scanner",
    icon: "Camera",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-image-compressor",
    name: "Image Compressor",
    category: "browser-tools",
    description: "Compress JPG, PNG and WebP images locally, with no upload to a server.",
    officialUrl: "/tools/image-compressor",
    tags: ["image", "compress", "optimize"],
    pricing: "Free",
    internalToolSlug: "image-compressor",
    icon: "Image",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-pdf-tools",
    name: "PDF Tools",
    category: "browser-tools",
    description: "Merge, split, compress, and convert PDFs — a full private, in-browser PDF workspace.",
    officialUrl: "/tools/pdf-studio",
    tags: ["pdf", "merge", "compress"],
    pricing: "Free",
    internalToolSlug: "pdf-studio",
    icon: "FileStack",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-text-tools",
    name: "Text Tools",
    category: "browser-tools",
    description: "Clean, transform, count and de-duplicate text — a full text-utility workspace.",
    officialUrl: "/tools/text-cleaner",
    tags: ["text", "clean", "transform"],
    pricing: "Free",
    internalToolSlug: "text-cleaner",
    icon: "FileCode2",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-timestamp-converter",
    name: "Timestamp Converter",
    category: "browser-tools",
    description: "Convert between Unix timestamps and human-readable dates, across time zones.",
    officialUrl: "/tools/timestamp-converter",
    tags: ["timestamp", "unix", "date"],
    pricing: "Free",
    internalToolSlug: "timestamp-converter",
    icon: "Terminal",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-url-encoder",
    name: "URL Encoder/Decoder",
    category: "browser-tools",
    description: "Encode or decode URL components and query strings instantly.",
    officialUrl: "/tools/url-encoder",
    tags: ["url", "encode", "decode"],
    pricing: "Free",
    internalToolSlug: "url-encoder",
    icon: "Globe",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-color-picker",
    name: "Color Picker & Converter",
    category: "browser-tools",
    description: "Convert colors between HEX, RGB, HSL and more, with a live picker.",
    officialUrl: "/tools/color-converter",
    tags: ["color", "hex", "rgb"],
    pricing: "Free",
    internalToolSlug: "color-converter",
    icon: "Palette",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-gradient-generator",
    name: "Gradient Generator",
    category: "browser-tools",
    description: "Design linear and radial CSS gradients and copy production-ready code.",
    officialUrl: "/tools/gradient-generator",
    tags: ["css", "gradient", "generator"],
    pricing: "Free",
    internalToolSlug: "gradient-generator",
    icon: "Sparkles",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-lorem-ipsum",
    name: "Lorem Ipsum Generator",
    category: "browser-tools",
    description: "Generate placeholder paragraphs, sentences or word lists for mockups.",
    officialUrl: "/tools/lorem-ipsum-generator",
    tags: ["placeholder", "text", "generator"],
    pricing: "Free",
    internalToolSlug: "lorem-ipsum-generator",
    icon: "FileCode2",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-markdown-converter",
    name: "Markdown Converter",
    category: "browser-tools",
    description: "Convert Markdown to HTML or HTML back to Markdown, instantly.",
    officialUrl: "/tools/markdown-converter",
    tags: ["markdown", "html", "converter"],
    pricing: "Free",
    internalToolSlug: "markdown-converter",
    icon: "FileCode2",
    addedOn: "2026-07-31",
  },
  {
    slug: "builtin-csv-json-converter",
    name: "CSV to JSON Converter",
    category: "browser-tools",
    description: "Convert CSV to JSON or JSON back to CSV, with quoted-field support.",
    officialUrl: "/tools/csv-json-converter",
    tags: ["csv", "json", "converter"],
    pricing: "Free",
    internalToolSlug: "csv-json-converter",
    icon: "FileSpreadsheet",
    addedOn: "2026-07-31",
  },
];
