import type { DevResource } from "./types";

/**
 * The Developer Playground — built-in interactive CSS/code tools, shown as
 * their own section in the Developer Hub. Every entry links to a real,
 * working TechToolsCenter tool; nothing here is a placeholder.
 */
export const playgroundResources: DevResource[] = [
  {
    slug: "playground-ui-snippets",
    name: "UI Snippets",
    category: "browser-tools",
    description: "Ready-made buttons, toggles, sliders, cards, badges, avatars, loaders and alerts — live preview, copy the code.",
    officialUrl: "/tools/ui-snippets",
    tags: ["css", "components", "snippets", "ui kit"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "ui-snippets",
    icon: "LayoutTemplate",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-code-playground",
    name: "Code Playground",
    category: "browser-tools",
    description: "Write HTML, CSS and JS and see the result live in a sandboxed preview — like a mini CodePen.",
    officialUrl: "/tools/code-playground",
    tags: ["html", "css", "javascript", "live editor"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "code-playground",
    icon: "Code2",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-tailwind-playground",
    name: "Tailwind Playground",
    category: "browser-tools",
    description: "Try Tailwind CSS utility classes live, powered by the official Tailwind Play CDN.",
    officialUrl: "/tools/tailwind-playground",
    tags: ["tailwind", "css", "live preview"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "tailwind-playground",
    icon: "Wind",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-flexbox-generator",
    name: "Flexbox Generator",
    category: "browser-tools",
    description: "Design a CSS Flexbox layout visually and copy the code.",
    officialUrl: "/tools/flexbox-generator",
    tags: ["css", "flexbox", "layout"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "flexbox-generator",
    icon: "Columns3",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-grid-generator",
    name: "Grid Generator",
    category: "browser-tools",
    description: "Design a CSS Grid layout visually and copy the code.",
    officialUrl: "/tools/grid-generator",
    tags: ["css", "grid", "layout"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "grid-generator",
    icon: "Grid3x3",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-border-radius-generator",
    name: "Border Radius Generator",
    category: "browser-tools",
    description: "Design rounded corners visually — per corner or all at once.",
    officialUrl: "/tools/border-radius-generator",
    tags: ["css", "border-radius"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "border-radius-generator",
    icon: "Ruler",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-box-shadow-generator",
    name: "Box Shadow Generator",
    category: "browser-tools",
    description: "Design single or layered CSS box-shadows visually.",
    officialUrl: "/tools/box-shadow-generator",
    tags: ["css", "box-shadow"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "box-shadow-generator",
    icon: "Layers",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-glassmorphism-generator",
    name: "Glassmorphism Generator",
    category: "browser-tools",
    description: "Design a frosted-glass CSS effect visually and copy the code.",
    officialUrl: "/tools/glassmorphism-generator",
    tags: ["css", "glassmorphism", "backdrop-filter"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "glassmorphism-generator",
    icon: "Contrast",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-svg-blob-generator",
    name: "SVG Blob Generator",
    category: "browser-tools",
    description: "Generate random organic blob shapes as SVG for backgrounds and decoration.",
    officialUrl: "/tools/svg-blob-generator",
    tags: ["svg", "blob", "generator"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "svg-blob-generator",
    icon: "Shapes",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-svg-optimizer",
    name: "SVG Optimizer",
    category: "browser-tools",
    description: "Shrink SVG file size by removing comments, metadata and redundant markup.",
    officialUrl: "/tools/svg-optimizer",
    tags: ["svg", "optimizer", "minifier"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "svg-optimizer",
    icon: "FileCode2",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-gradient-generator",
    name: "Gradient Generator",
    category: "browser-tools",
    description: "Design linear and radial CSS gradients visually and copy the code.",
    officialUrl: "/tools/gradient-generator",
    tags: ["css", "gradient"],
    pricing: "Free",
    internalToolSlug: "gradient-generator",
    icon: "Blend",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-color-palette-generator",
    name: "Color Palette Generator",
    category: "browser-tools",
    description: "Generate harmonious colour palettes from a base colour.",
    officialUrl: "/tools/color-palette-generator",
    tags: ["css", "color", "palette"],
    pricing: "Free",
    internalToolSlug: "color-palette-generator",
    icon: "Palette",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-meta-tags-generator",
    name: "Meta Tag & Open Graph Generator",
    category: "browser-tools",
    description: "Generate SEO meta, Open Graph and Twitter Card tags for any page.",
    officialUrl: "/tools/meta-tags-generator",
    tags: ["seo", "meta tags", "open graph"],
    pricing: "Free",
    internalToolSlug: "meta-tags-generator",
    icon: "Tags",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-schema-generator",
    name: "Schema / JSON-LD Generator",
    category: "browser-tools",
    description: "Generate valid Schema.org JSON-LD structured data for common page types.",
    officialUrl: "/tools/schema-generator",
    tags: ["seo", "json-ld", "structured data"],
    pricing: "Free",
    internalToolSlug: "schema-generator",
    icon: "Braces",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-robots-txt-generator",
    name: "robots.txt Generator",
    category: "browser-tools",
    description: "Build a robots.txt with crawl rules and your sitemap URL.",
    officialUrl: "/tools/robots-txt-generator",
    tags: ["seo", "robots.txt", "crawling"],
    pricing: "Free",
    internalToolSlug: "robots-txt-generator",
    icon: "Bot",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-sitemap-generator",
    name: "Sitemap.xml Generator",
    category: "browser-tools",
    description: "Build a sitemap.xml file from a list of URLs, with changefreq and priority.",
    officialUrl: "/tools/sitemap-generator",
    tags: ["seo", "sitemap", "xml"],
    pricing: "Free",
    badge: "New",
    internalToolSlug: "sitemap-generator",
    icon: "ListTree",
    addedOn: "2026-07-31",
  },
  {
    slug: "playground-favicon-generator",
    name: "Favicon & Manifest Generator",
    category: "browser-tools",
    description: "Generate a full favicon set plus a ready-to-use web app manifest.",
    officialUrl: "/tools/favicon-generator",
    tags: ["favicon", "manifest", "pwa"],
    pricing: "Free",
    internalToolSlug: "favicon-generator",
    icon: "AppWindow",
    addedOn: "2026-07-31",
  },
];
