import type { IndiaService } from "./types";

/**
 * India Services registry — an educational, navigation-only directory.
 * TechToolsCenter does NOT provide these services, collect applications or take
 * payments. Every entry links out to the official government website.
 * Fees/timelines are included only where publicly/officially published.
 */
export const indiaServices: IndiaService[] = [
  /* ---------------- Identity Documents ---------------- */
  {
    slug: "aadhaar-card",
    name: "Aadhaar Card",
    category: "identity-documents",
    officialName: "UIDAI (Unique Identification Authority of India)",
    officialUrl: "https://uidai.gov.in",
    overview:
      "Aadhaar is a 12-digit unique identity number issued by UIDAI to residents of India. It is used as proof of identity and address for a wide range of services. New enrolment is done at an Aadhaar centre; most updates (address, mobile, email, name, etc.) can be started online on the official UIDAI portal.",
    documents: ["Proof of identity (e.g. passport, PAN, voter ID)", "Proof of address (e.g. bank statement, utility bill)", "Proof of date of birth (for some updates)", "Existing Aadhaar number (for updates)"],
    eligibility: ["Any resident of India, including infants and children", "NRIs with a valid Indian passport"],
    steps: [
      "Visit the official UIDAI portal (uidai.gov.in).",
      "For new enrolment, locate the nearest Aadhaar Seva Kendra and book an appointment.",
      "For updates, sign in with your Aadhaar number and OTP.",
      "Choose what to update (address, mobile, name, etc.) and upload supporting documents.",
      "Submit and note your Update Request Number (URN) to track status.",
    ],
    fees: "Document update: ₹50 (online/at centre); biometric update: ₹100 (as published by UIDAI). New enrolment is free.",
    processingTime: "Updates are typically processed within about 30 days (per UIDAI).",
    faq: [
      { question: "How do I update my Aadhaar address online?", answer: "Sign in on uidai.gov.in with your Aadhaar and OTP, choose 'Update Address', upload a valid address proof, and submit. You'll get a URN to track it." },
      { question: "I lost my Aadhaar — how do I get it again?", answer: "Use the 'Retrieve Aadhaar/EID' option on uidai.gov.in with your registered mobile, or download your e-Aadhaar after verifying via OTP." },
      { question: "Is Aadhaar enrolment free?", answer: "Yes, first-time enrolment is free. Updates carry a small official fee." },
    ],
    mistakes: ["Uploading blurry or unaccepted documents", "Not keeping the mobile number linked/active for OTP", "Sharing your Aadhaar OTP with anyone"],
    relatedServices: ["pan-card", "pan-aadhaar-link", "voter-id", "digilocker"],
    relatedBlog: ["how-to-update-aadhaar-address-online"],
    relatedTools: ["image-compressor-for-aadhar-card", "image-compressor", "image-resizer", "pdf-compress"],
    keywords: ["aadhaar", "aadhar card", "uidai", "aadhaar update", "aadhaar address change", "lost aadhaar", "e-aadhaar"],
    popular: true,
    updatedOn: "2026-07-18",
  },
  {
    slug: "pan-card",
    name: "PAN Card",
    category: "identity-documents",
    officialName: "Income Tax Department (via Protean/UTIITSL)",
    officialUrl: "https://www.incometax.gov.in",
    overview:
      "PAN (Permanent Account Number) is a 10-character alphanumeric identifier issued by the Income Tax Department, required for filing taxes and many financial transactions. You can apply for a new PAN, get an instant e-PAN using Aadhaar, or make corrections online.",
    documents: ["Aadhaar (for instant e-PAN)", "Proof of identity", "Proof of address", "Proof of date of birth", "Passport-size photograph (for physical card)"],
    eligibility: ["Indian citizens and entities", "Foreign citizens/entities with taxable income in India"],
    steps: [
      "Go to the official Income Tax e-filing portal (incometax.gov.in).",
      "For instant e-PAN, choose 'Instant e-PAN' and verify via Aadhaar OTP.",
      "For a new PAN or correction, apply via the authorised agencies (Protean/NSDL or UTIITSL).",
      "Fill in your details, upload documents and pay the fee (if applicable).",
      "Track the application with your acknowledgement number.",
    ],
    fees: "Instant e-PAN via Aadhaar is free. Physical PAN application fees are published by Protean/UTIITSL.",
    processingTime: "Instant e-PAN: within minutes. Physical PAN: usually around 15 working days.",
    faq: [
      { question: "Can I get a PAN card for free?", answer: "Yes — the Instant e-PAN service on the Income Tax portal issues a PDF e-PAN free of cost using your Aadhaar." },
      { question: "How do I correct my name/DOB on PAN?", answer: "Use the 'Changes/Correction in PAN' application via Protean (NSDL) or UTIITSL and upload supporting proof." },
      { question: "Is a photo needed for e-PAN?", answer: "No, the instant e-PAN uses your Aadhaar details. A photo is needed only for a physical card application." },
    ],
    mistakes: ["Applying on unofficial third-party sites that charge extra", "Mismatched name/DOB between PAN and Aadhaar", "Uploading an oversized photo/signature that gets rejected"],
    relatedServices: ["aadhaar-card", "pan-aadhaar-link", "itr-filing", "gst-registration"],
    relatedBlog: ["how-to-apply-pan-card-online-free"],
    relatedTools: ["image-compressor-for-pan-card", "image-compressor", "image-resizer", "pdf-compress"],
    keywords: ["pan card", "pan", "instant e-pan", "pan correction", "income tax pan", "apply pan"],
    popular: true,
    updatedOn: "2026-07-18",
  },
  {
    slug: "voter-id",
    name: "Voter ID (EPIC)",
    category: "identity-documents",
    officialName: "Election Commission of India",
    officialUrl: "https://voters.eci.gov.in",
    overview:
      "The Voter ID (EPIC) lets eligible citizens vote and serves as identity/address proof. New registration, corrections and address transfers are handled online through the Election Commission's Voter Services Portal.",
    documents: ["Proof of age", "Proof of address", "Passport-size photograph", "Aadhaar (for linking, optional)"],
    eligibility: ["Indian citizen aged 18 years or above on the qualifying date", "Ordinarily resident of the constituency"],
    steps: [
      "Visit the official Voter Services Portal (voters.eci.gov.in).",
      "Register/sign in with your mobile number.",
      "For new voters, fill Form 6; for corrections, Form 8.",
      "Upload your photo and supporting documents.",
      "Submit and track your application reference number.",
    ],
    faq: [
      { question: "How do I check if my name is on the voter list?", answer: "Use the 'Search in Electoral Roll' option on voters.eci.gov.in with your details or EPIC number." },
      { question: "Can I change my address on Voter ID?", answer: "Yes, use Form 8 on the portal to update address within or across constituencies." },
    ],
    mistakes: ["Submitting a photo that doesn't meet specifications", "Duplicate applications while one is already in process"],
    relatedServices: ["aadhaar-card", "pan-card"],
    relatedTools: ["image-compressor", "image-resizer", "image-converter"],
    keywords: ["voter id", "epic", "voter registration", "electoral roll", "form 6", "election commission"],
    updatedOn: "2026-07-18",
  },
  {
    slug: "passport",
    name: "Passport",
    category: "travel-immigration",
    officialName: "Passport Seva, Ministry of External Affairs",
    officialUrl: "https://www.passportindia.gov.in",
    overview:
      "An Indian passport is issued by the Ministry of External Affairs through Passport Seva. You apply online, book an appointment at a Passport Seva Kendra (PSK) or Post Office PSK, and complete document verification in person.",
    documents: ["Proof of address (e.g. Aadhaar, utility bill)", "Proof of date of birth (e.g. birth certificate, PAN)", "Identity proof", "Recent passport-size photographs (as per specs)"],
    eligibility: ["Indian citizens", "Minors (with parents' documents and consent)"],
    steps: [
      "Register on the official Passport Seva portal (passportindia.gov.in).",
      "Fill the application form for Fresh/Reissue.",
      "Pay the fee online and book a PSK appointment.",
      "Visit the PSK with original documents for verification.",
      "Track your application and police verification status online.",
    ],
    fees: "Fees vary by booklet type and pages and are shown on the Passport Seva portal during payment.",
    processingTime: "Varies; Tatkaal is faster. Timelines and police verification depend on your case.",
    faq: [
      { question: "What photo size is needed for a passport?", answer: "Follow the exact specification shown on the Passport Seva portal. You can prepare a compliant photo before your appointment." },
      { question: "Can I reschedule my PSK appointment?", answer: "Yes, the portal allows a limited number of appointment reschedules." },
    ],
    mistakes: ["Name/DOB mismatch across documents", "Carrying photocopies instead of originals to the PSK", "Uploading a non-compliant photograph"],
    relatedServices: ["police-clearance-certificate", "aadhaar-card", "pan-card", "birth-certificate"],
    relatedBlog: ["document-photo-size-government-forms"],
    relatedTools: ["image-compressor-for-passport-photo", "resize-image-for-passport", "image-compressor", "pdf-compress"],
    keywords: ["passport", "passport seva", "apply passport", "passport renewal", "psk appointment", "tatkaal passport"],
    popular: true,
    updatedOn: "2026-07-18",
  },

  /* ---------------- Certificates ---------------- */
  {
    slug: "birth-certificate",
    name: "Birth Certificate",
    category: "certificates",
    officialName: "Civil Registration System (crsorgi.gov.in) / State portals",
    officialUrl: "https://crsorgi.gov.in",
    overview:
      "A birth certificate is an essential legal document registering a birth. Registration is done through the Civil Registration System or your State/municipal portal. Recent births can be registered online in many states; older records are obtained from the local registrar.",
    documents: ["Hospital/institution birth proof", "Parents' identity and address proof", "Application form as per state"],
    eligibility: ["Any registered birth in India", "Applications by parents/guardians"],
    steps: [
      "Visit the Civil Registration System portal (crsorgi.gov.in) or your state/municipal portal.",
      "Register and select 'Birth' registration/certificate.",
      "Enter the birth details and upload supporting documents.",
      "Submit to the local registrar for verification.",
      "Download or collect the certificate once approved.",
    ],
    faq: [
      { question: "Where do I apply for a birth certificate?", answer: "Through the Civil Registration System (crsorgi.gov.in) or your state/municipal corporation portal, depending on where the birth occurred." },
      { question: "Can I get an old birth certificate?", answer: "Yes, contact the local registrar/municipal office where the birth was registered; some states offer online records." },
    ],
    mistakes: ["Applying on the wrong state portal", "Spelling mismatches with hospital records"],
    relatedServices: ["income-certificate", "aadhaar-card"],
    relatedTools: ["pdf-compress", "image-compressor", "image-converter"],
    keywords: ["birth certificate", "crs", "birth registration", "municipal certificate"],
    updatedOn: "2026-07-18",
  },
  {
    slug: "income-certificate",
    name: "Income Certificate",
    category: "certificates",
    officialName: "State Government e-District portals",
    officialUrl: "https://services.india.gov.in",
    overview:
      "An income certificate certifies a family's annual income and is issued by the respective State Government (usually via the e-District/Revenue portal). It is commonly required for scholarships, reservations and welfare schemes.",
    documents: ["Identity proof", "Address proof", "Income proof (salary slip / self-declaration as required)", "Ration card (in some states)"],
    eligibility: ["Residents of the issuing state", "As per state-specific rules"],
    steps: [
      "Find your State's e-District/Revenue portal (linked from the National Services directory).",
      "Register and select 'Income Certificate'.",
      "Fill the application and upload supporting documents.",
      "Submit to the Tehsildar/Revenue office for verification.",
      "Download the digitally-signed certificate once issued.",
    ],
    faq: [
      { question: "Which portal issues an income certificate?", answer: "It's issued by your State Government's e-District/Revenue portal — the exact site depends on your state." },
      { question: "How long is an income certificate valid?", answer: "Validity is state-specific, often up to one financial year." },
    ],
    mistakes: ["Using another state's portal", "Declaring inconsistent income figures"],
    relatedServices: ["caste-certificate", "ews-certificate", "domicile-certificate", "scholarship"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["income certificate", "e-district", "revenue certificate", "annual income proof"],
    updatedOn: "2026-07-18",
  },
  {
    slug: "caste-certificate",
    name: "Caste Certificate",
    category: "certificates",
    officialName: "State Government e-District portals",
    officialUrl: "https://services.india.gov.in",
    overview:
      "A caste certificate certifies a person's community (SC/ST/OBC) and is issued by the State Government. It is required for reservations in education, jobs and welfare schemes. Apply through your state's e-District/Revenue portal.",
    documents: ["Identity and address proof", "Proof of caste (family records/parent's certificate)", "Ration card / school records (as required)"],
    eligibility: ["Applicants belonging to a notified community", "As per state rules"],
    steps: [
      "Open your State's e-District/Revenue portal.",
      "Register and select 'Caste Certificate'.",
      "Fill details and upload proof of community.",
      "Submit for verification by the Revenue authority.",
      "Download the issued certificate.",
    ],
    faq: [
      { question: "Is the caste certificate valid across states?", answer: "It is issued by your home state; use in another state may need re-verification per rules." },
    ],
    mistakes: ["Missing parental/ancestral proof", "Applying in the wrong jurisdiction"],
    relatedServices: ["income-certificate", "ews-certificate", "domicile-certificate", "scholarship"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["caste certificate", "sc st obc certificate", "community certificate", "reservation certificate"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- Business & Tax ---------------- */
  {
    slug: "gst-registration",
    name: "GST Registration",
    category: "business-tax",
    officialName: "Goods and Services Tax Network (GSTN)",
    officialUrl: "https://www.gst.gov.in",
    overview:
      "GST registration is required for businesses crossing the prescribed turnover threshold or making inter-state supplies. Registration is done free of cost on the official GST portal and issues a GSTIN.",
    documents: ["PAN of the business/proprietor", "Aadhaar", "Proof of business address", "Bank account details", "Photograph and constitution proof (partnership deed/COI as applicable)"],
    eligibility: ["Businesses above the turnover threshold", "Inter-state suppliers, e-commerce sellers and others as specified"],
    steps: [
      "Go to the official GST portal (gst.gov.in) and start a New Registration.",
      "Complete Part A with PAN, mobile and email (OTP verified).",
      "Fill Part B with business details and upload documents.",
      "Complete Aadhaar authentication.",
      "Track the ARN; on approval, download your GST certificate with GSTIN.",
    ],
    fees: "GST registration on the official portal is free of cost.",
    processingTime: "Usually processed within about 7 working days (subject to verification).",
    faq: [
      { question: "Is GST registration free?", answer: "Yes, registration on the official gst.gov.in portal is free. Third-party agents may charge a service fee." },
      { question: "Do I need GST for a small business?", answer: "Only if you cross the turnover threshold or fall under a category that mandates registration (e.g. inter-state supply, e-commerce)." },
    ],
    mistakes: ["Entering a business name that doesn't match PAN", "Skipping Aadhaar authentication", "Uploading unclear address proof"],
    relatedServices: ["msme-udyam", "itr-filing", "pan-card"],
    relatedTools: ["invoice-maker", "gst-calculator", "pdf-compress"],
    relatedBlog: ["how-to-create-gst-invoice-online-free"],
    keywords: ["gst registration", "gstin", "gst number", "register gst", "gst portal"],
    popular: true,
    updatedOn: "2026-07-18",
  },
  {
    slug: "msme-udyam",
    name: "Udyam (MSME) Registration",
    category: "business-tax",
    officialName: "Ministry of MSME",
    officialUrl: "https://udyamregistration.gov.in",
    overview:
      "Udyam Registration is the official recognition for Micro, Small and Medium Enterprises (MSMEs). It is free, paperless and based on self-declaration using Aadhaar and PAN, and unlocks various government benefits and schemes.",
    documents: ["Aadhaar of the proprietor/authorised signatory", "PAN", "Business/bank details (self-declared)"],
    eligibility: ["Micro, small or medium enterprises as per the official investment/turnover criteria"],
    steps: [
      "Visit the official Udyam portal (udyamregistration.gov.in).",
      "Choose 'New Registration' and verify with Aadhaar OTP.",
      "Enter PAN and validate.",
      "Fill business details (self-declared) and submit.",
      "Download your Udyam Registration Certificate with its unique number.",
    ],
    fees: "Udyam registration is completely free on the official portal.",
    faq: [
      { question: "Is there any fee for Udyam registration?", answer: "No. The official Udyam portal charges nothing. Beware of third-party sites asking for fees." },
      { question: "Do I need documents to upload?", answer: "No uploads are needed — it's based on self-declaration with Aadhaar and PAN." },
    ],
    mistakes: ["Paying a third-party site for a free service", "Aadhaar/PAN mismatch"],
    relatedServices: ["gst-registration", "itr-filing"],
    relatedTools: ["invoice-maker", "quotation-generator", "brand-kit-generator"],
    keywords: ["udyam", "msme registration", "udyam aadhaar", "msme certificate", "small business registration"],
    updatedOn: "2026-07-18",
  },
  {
    slug: "itr-filing",
    name: "Income Tax Return (ITR) Filing",
    category: "business-tax",
    officialName: "Income Tax Department",
    officialUrl: "https://www.incometax.gov.in",
    overview:
      "Filing an Income Tax Return (ITR) reports your income and taxes for a financial year. Individuals and businesses file directly on the official Income Tax e-filing portal, often using pre-filled data.",
    documents: ["PAN and Aadhaar (linked)", "Form 16 / salary details", "Bank interest and investment proofs", "Details of other income and deductions"],
    eligibility: ["Anyone with taxable income or meeting mandatory filing conditions"],
    steps: [
      "Log in to the official e-filing portal (incometax.gov.in).",
      "Select the correct ITR form for your income type.",
      "Review pre-filled data and add income/deduction details.",
      "Verify tax computation and submit.",
      "e-Verify the return (via Aadhaar OTP, net banking, etc.).",
    ],
    faq: [
      { question: "Which ITR form should I use?", answer: "It depends on your income sources; the portal guides you, or consult a tax professional." },
      { question: "Is e-verification mandatory?", answer: "Yes — your return must be verified (ideally e-verified) for it to be processed." },
    ],
    mistakes: ["Missing the filing due date", "Not e-verifying after submission", "PAN–Aadhaar not linked"],
    relatedServices: ["pan-card", "pan-aadhaar-link", "gst-registration"],
    relatedTools: ["gst-calculator", "percentage-calculator", "pdf-compress"],
    keywords: ["itr", "income tax return", "file itr", "e-filing", "tax filing"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- Healthcare ---------------- */
  {
    slug: "abha-health-id",
    name: "ABHA Health ID",
    category: "healthcare",
    officialName: "Ayushman Bharat Digital Mission (ABDM)",
    officialUrl: "https://abha.abdm.gov.in",
    overview:
      "ABHA (Ayushman Bharat Health Account) is a unique health ID under the Ayushman Bharat Digital Mission that lets you link and access your health records digitally. Creating an ABHA number is free using Aadhaar or a mobile number.",
    documents: ["Aadhaar or a driving licence", "Mobile number for OTP"],
    eligibility: ["Any Indian resident"],
    steps: [
      "Visit the official ABHA portal (abha.abdm.gov.in).",
      "Choose to create ABHA using Aadhaar or mobile.",
      "Verify with OTP.",
      "Complete your profile and note your 14-digit ABHA number.",
      "Link your health records via ABDM-enabled facilities.",
    ],
    fees: "Creating an ABHA number is free.",
    faq: [
      { question: "Is ABHA mandatory?", answer: "No, it's voluntary. It simply makes managing your digital health records easier." },
      { question: "Can I create ABHA without Aadhaar?", answer: "Yes, you can create it using your mobile number as well." },
    ],
    mistakes: ["Sharing your ABHA OTP", "Creating multiple ABHA numbers"],
    relatedServices: ["ayushman-bharat", "digilocker"],
    relatedTools: ["image-compressor", "pdf-compress"],
    keywords: ["abha", "health id", "abdm", "ayushman bharat health account", "digital health id"],
    updatedOn: "2026-07-18",
  },
  {
    slug: "ayushman-bharat",
    name: "Ayushman Bharat (PM-JAY)",
    category: "healthcare",
    officialName: "National Health Authority (PM-JAY)",
    officialUrl: "https://pmjay.gov.in",
    overview:
      "Ayushman Bharat PM-JAY provides health cover for eligible families at empanelled hospitals. You can check eligibility and find your Ayushman card details through the official PM-JAY/beneficiary portal.",
    documents: ["Aadhaar / ration card for verification", "Mobile number"],
    eligibility: ["Families identified as eligible per the official beneficiary database (SECC/added categories)"],
    steps: [
      "Visit the official PM-JAY portal (pmjay.gov.in).",
      "Use 'Am I Eligible' to check your status.",
      "Verify identity via OTP.",
      "Locate an empanelled hospital for cashless treatment.",
      "Get your Ayushman card via the official beneficiary portal.",
    ],
    faq: [
      { question: "How do I check Ayushman Bharat eligibility?", answer: "Use the 'Am I Eligible' tool on the official pmjay.gov.in portal with your mobile number." },
      { question: "Is treatment cashless?", answer: "Yes, eligible beneficiaries receive cashless treatment at empanelled hospitals up to the scheme limit." },
    ],
    mistakes: ["Relying on unofficial 'card makers'", "Not verifying the hospital is empanelled"],
    relatedServices: ["abha-health-id"],
    relatedTools: ["image-compressor", "pdf-compress"],
    keywords: ["ayushman bharat", "pmjay", "ayushman card", "health insurance scheme", "golden card"],
    popular: true,
    updatedOn: "2026-07-18",
  },

  /* ---------------- Employment ---------------- */
  {
    slug: "epfo",
    name: "EPFO / Provident Fund (PF)",
    category: "employment",
    officialName: "Employees' Provident Fund Organisation",
    officialUrl: "https://www.epfindia.gov.in",
    overview:
      "EPFO manages the Provident Fund for salaried employees. Using your UAN (Universal Account Number) on the member portal, you can check your PF balance, update KYC, and file transfer or withdrawal claims.",
    documents: ["UAN (Universal Account Number)", "Aadhaar, PAN and bank details linked to UAN"],
    eligibility: ["Salaried employees covered under EPF"],
    steps: [
      "Visit the official EPFO member portal (linked from epfindia.gov.in).",
      "Activate/sign in with your UAN and password.",
      "Complete KYC (Aadhaar, PAN, bank) and get it verified by the employer.",
      "Use online services to view passbook, transfer or claim.",
      "Track your claim status online.",
    ],
    faq: [
      { question: "How do I check my PF balance?", answer: "Sign in to the EPFO member portal with your UAN, or use the official UMANG app / passbook service." },
      { question: "How do I withdraw PF online?", answer: "With a KYC-verified UAN, file a claim (Form 19/10C/31) on the member portal." },
    ],
    mistakes: ["Incomplete/unverified KYC", "Mismatched name across Aadhaar, PAN and bank"],
    relatedServices: ["eshram", "aadhaar-card"],
    relatedTools: ["emi-calculator", "percentage-calculator", "pdf-compress"],
    keywords: ["epfo", "pf", "provident fund", "uan", "pf balance", "pf withdrawal"],
    popular: true,
    updatedOn: "2026-07-18",
  },
  {
    slug: "eshram",
    name: "eShram Card",
    category: "employment",
    officialName: "Ministry of Labour & Employment",
    officialUrl: "https://eshram.gov.in",
    overview:
      "The eShram card registers unorganised-sector workers in a national database, giving them a Universal Account Number (UAN) and access to social-security benefits. Registration is free using Aadhaar.",
    documents: ["Aadhaar", "Mobile number linked to Aadhaar", "Bank account details"],
    eligibility: ["Unorganised-sector workers aged 16–59", "Not a member of EPFO/ESIC or an income-tax payer (as per scheme rules)"],
    steps: [
      "Visit the official eShram portal (eshram.gov.in).",
      "Choose 'Register on eShram' and verify with Aadhaar OTP.",
      "Fill in personal, occupation and bank details.",
      "Submit and download your eShram card with UAN.",
    ],
    fees: "Registration is free.",
    faq: [
      { question: "Who can register on eShram?", answer: "Unorganised workers such as construction workers, street vendors, domestic workers, farmers and more, within the eligible age and criteria." },
      { question: "Is there any fee?", answer: "No, eShram registration is free on the official portal." },
    ],
    mistakes: ["Mobile not linked to Aadhaar (OTP fails)", "Registering while ineligible (EPFO/ESIC member)"],
    relatedServices: ["epfo"],
    relatedTools: ["image-compressor", "pdf-compress"],
    keywords: ["eshram", "e-shram card", "unorganised worker", "labour card", "shram card"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- Education ---------------- */
  {
    slug: "scholarship",
    name: "National Scholarship (NSP)",
    category: "education",
    officialName: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in",
    overview:
      "The National Scholarship Portal (NSP) is a single platform for various central and state scholarship schemes for students. Students register, apply and track scholarships in one place.",
    documents: ["Aadhaar / enrolment ID", "Bank account details", "Income and caste certificates (as required)", "Previous marksheet and institution details"],
    eligibility: ["Students meeting the specific scheme criteria (income, category, course, etc.)"],
    steps: [
      "Visit the official National Scholarship Portal (scholarships.gov.in).",
      "Complete fresh registration with your details.",
      "Select the applicable scholarship scheme.",
      "Upload required documents and submit before the deadline.",
      "Track your application status on the portal.",
    ],
    faq: [
      { question: "Can I apply for multiple scholarships?", answer: "You typically apply for the scheme you're eligible for; the portal prevents duplicate/ineligible applications." },
      { question: "What if I miss the deadline?", answer: "Applications close on the published date; watch the NSP portal for each scheme's timeline." },
    ],
    mistakes: ["Wrong bank/IFSC details (payment fails)", "Uploading unclear certificates", "Missing the scheme deadline"],
    relatedServices: ["income-certificate", "caste-certificate"],
    relatedTools: ["image-compressor", "pdf-compress", "image-resizer"],
    keywords: ["scholarship", "nsp", "national scholarship portal", "student scholarship", "scholarships.gov.in"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- Vehicles ---------------- */
  {
    slug: "driving-licence",
    name: "Driving Licence",
    category: "vehicles",
    officialName: "Parivahan Sewa (Ministry of Road Transport & Highways)",
    officialUrl: "https://sarathi.parivahan.gov.in",
    overview:
      "Driving licence services — learner's licence, permanent licence, renewal and address change — are handled on the official Sarathi (Parivahan) portal, along with an RTO test where required.",
    documents: ["Proof of age and address", "Passport-size photographs", "Learner's licence (for permanent DL)", "Medical certificate (where applicable)"],
    eligibility: ["Minimum age as per licence type", "Passing the applicable test"],
    steps: [
      "Visit the official Sarathi portal (sarathi.parivahan.gov.in) and select your state.",
      "Apply for Learner's Licence and take the online test.",
      "After the mandatory period, apply for the Permanent Licence.",
      "Book a slot and pass the driving test at the RTO.",
      "Track and download your licence status online.",
    ],
    fees: "Fees are shown on the Parivahan portal during payment.",
    faq: [
      { question: "How do I get a learner's licence?", answer: "Apply on the Sarathi portal, upload documents, pay the fee and take the online learner's test." },
      { question: "Can I renew my DL online?", answer: "Yes, renewal and address change can be initiated on the Parivahan/Sarathi portal." },
    ],
    mistakes: ["Selecting the wrong state on Parivahan", "Non-compliant photo/signature uploads", "Booking the RTO test before eligibility"],
    relatedServices: ["vehicle-rc", "e-challan", "aadhaar-card"],
    relatedTools: ["image-compressor-for-passport-photo", "image-studio", "pdf-merge", "image-compressor"],
    keywords: ["driving licence", "learner licence", "dl", "sarathi", "parivahan", "dl renewal"],
    popular: true,
    updatedOn: "2026-07-18",
  },
  {
    slug: "vehicle-rc",
    name: "Vehicle RC Services",
    category: "vehicles",
    officialName: "Parivahan Sewa (VAHAN)",
    officialUrl: "https://vahan.parivahan.gov.in",
    overview:
      "Vehicle Registration Certificate (RC) services — new registration, ownership transfer, address change, duplicate RC and more — are available on the official VAHAN (Parivahan) portal.",
    documents: ["Proof of identity and address", "Insurance and PUC (as required)", "Existing RC (for transfers/updates)"],
    eligibility: ["Registered vehicle owners", "As per RTO rules"],
    steps: [
      "Visit the official VAHAN portal (vahan.parivahan.gov.in) and select your state/RTO.",
      "Choose the required RC service.",
      "Fill the form and upload documents.",
      "Pay the applicable fee.",
      "Track your application at the RTO.",
    ],
    faq: [
      { question: "How do I transfer vehicle ownership?", answer: "Use the ownership transfer service on the VAHAN portal with the RC, insurance and required documents." },
    ],
    mistakes: ["Wrong RTO selection", "Expired insurance/PUC at time of service"],
    relatedServices: ["driving-licence", "e-challan", "fastag"],
    relatedTools: ["pdf-merge", "pdf-compress", "image-compressor"],
    keywords: ["rc", "vehicle registration", "vahan", "rc transfer", "duplicate rc", "parivahan"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- Agriculture ---------------- */
  {
    slug: "pm-kisan",
    name: "PM-KISAN",
    category: "agriculture",
    officialName: "Ministry of Agriculture & Farmers Welfare",
    officialUrl: "https://pmkisan.gov.in",
    overview:
      "PM-KISAN provides income support to eligible landholding farmer families. Farmers can register, complete e-KYC and check beneficiary status on the official PM-KISAN portal.",
    documents: ["Aadhaar", "Land records", "Bank account details"],
    eligibility: ["Landholding farmer families as per scheme rules (with certain exclusions)"],
    steps: [
      "Visit the official PM-KISAN portal (pmkisan.gov.in).",
      "Use 'New Farmer Registration'.",
      "Complete e-KYC (Aadhaar OTP).",
      "Enter land and bank details.",
      "Check 'Beneficiary Status' to track instalments.",
    ],
    faq: [
      { question: "How do I check PM-KISAN status?", answer: "Use 'Beneficiary Status' on the official pmkisan.gov.in portal with your registered number/Aadhaar." },
      { question: "Is e-KYC mandatory?", answer: "Yes, e-KYC is required to receive instalments." },
    ],
    mistakes: ["Skipping e-KYC", "Incorrect bank/Aadhaar linkage"],
    relatedServices: ["aadhaar-card"],
    relatedTools: ["image-compressor", "pdf-compress"],
    keywords: ["pm kisan", "pm-kisan", "kisan samman nidhi", "farmer scheme", "pmkisan status"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- Digital India ---------------- */
  {
    slug: "digilocker",
    name: "DigiLocker",
    category: "digital-india",
    officialName: "Ministry of Electronics & IT (MeitY)",
    officialUrl: "https://www.digilocker.gov.in",
    overview:
      "DigiLocker is a government platform to store and access digital documents (like Aadhaar, driving licence, marksheets and vehicle RC) issued by authorities. DigiLocker documents are legally at par with originals.",
    documents: ["Aadhaar / mobile number to create an account"],
    eligibility: ["Any Indian resident with a mobile number"],
    steps: [
      "Visit the official DigiLocker site (digilocker.gov.in) or app.",
      "Sign up using your mobile number and Aadhaar.",
      "Set a security PIN.",
      "Fetch issued documents from partner departments.",
      "Share or download verified documents when needed.",
    ],
    fees: "DigiLocker is free.",
    faq: [
      { question: "Are DigiLocker documents valid?", answer: "Yes, documents issued to DigiLocker are legally recognised at par with the physical originals." },
      { question: "Which documents can I fetch?", answer: "Aadhaar, PAN (verification), driving licence, RC, marksheets and more, from participating issuers." },
    ],
    mistakes: ["Sharing your DigiLocker PIN/OTP", "Using unofficial look-alike apps"],
    relatedServices: ["aadhaar-card", "driving-licence"],
    relatedTools: ["pdf-compress", "image-compressor", "image-converter"],
    keywords: ["digilocker", "digital documents", "digilocker aadhaar", "document wallet"],
    updatedOn: "2026-07-18",
  },
  {
    slug: "india-gov-portal",
    name: "National Government Services Portal",
    category: "government-portals",
    officialName: "National Portal of India",
    officialUrl: "https://www.india.gov.in",
    overview:
      "The National Portal of India is the official gateway to central and state government information and services. Use it to discover departments, schemes and official service links across India.",
    documents: [],
    eligibility: ["Open to everyone"],
    steps: [
      "Visit the official National Portal of India (india.gov.in).",
      "Browse services by category, ministry or state.",
      "Follow the official links to the relevant department's site.",
    ],
    faq: [
      { question: "What is india.gov.in?", answer: "It's the official National Portal of India — a single directory of government information and service links." },
    ],
    mistakes: ["Following unofficial mirror sites"],
    relatedServices: ["digilocker"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["national portal", "india.gov.in", "government services directory", "govt portals"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- More Certificates ---------------- */
  {
    slug: "marriage-certificate",
    name: "Marriage Certificate",
    category: "certificates",
    officialName: "State Government / Municipal e-District portals",
    officialUrl: "https://services.india.gov.in",
    overview:
      "A marriage certificate is the legal proof of a registered marriage in India. Marriages are registered either under the Hindu Marriage Act, 1955 (for Hindus, Buddhists, Jains and Sikhs) or the Special Marriage Act, 1954 (for inter-faith and civil marriages). Registration is handled by your State Government / Municipal Corporation, usually through the state's e-District or marriage-registration portal. A registered marriage certificate is required for visas, passports, name changes, joint bank accounts, insurance and legal matters.",
    documents: [
      "Marriage invitation card / proof of marriage",
      "Age proof of both spouses (birth certificate, PAN or 10th marksheet)",
      "Address proof of both spouses (Aadhaar, voter ID, etc.)",
      "Passport-size photographs of both spouses",
      "Marriage photograph together",
      "Two witnesses with their ID and address proof",
      "Affidavit of marriage (in some states)",
    ],
    eligibility: [
      "The marriage must have already taken place",
      "Groom aged 21+ and bride aged 18+",
      "Both parties must be legally eligible to marry (not already married, of sound mind)",
    ],
    steps: [
      "Find your State/Municipal marriage-registration or e-District portal (linked from the National Services directory).",
      "Register and choose the applicable Act (Hindu Marriage Act or Special Marriage Act).",
      "Fill the application with both spouses' and witnesses' details.",
      "Upload the required documents and photographs.",
      "Book an appointment at the Sub-Registrar / Marriage Officer's office (if required).",
      "Visit with both spouses and witnesses on the appointment date for verification.",
      "Collect or download the digitally-signed marriage certificate once approved.",
    ],
    fees: "A nominal registration fee applies and varies by state (often ₹100–₹500). Exact fees are shown on your state portal.",
    processingTime: "Under the Hindu Marriage Act, registration can be quick (often the same day/within a few days). Under the Special Marriage Act, a 30-day public notice period usually applies before the certificate is issued.",
    validity: "A marriage certificate is a permanent legal document and does not expire.",
    applyModes: ["Online (state e-District portal)", "Offline (Sub-Registrar / Municipal office)"],
    faq: [
      { question: "Is marriage registration mandatory in India?", answer: "Following Supreme Court directions, most states have made marriage registration compulsory. Even where it isn't strictly mandatory, a registered certificate is essential for passports, visas, insurance and legal purposes." },
      { question: "What is the difference between the Hindu Marriage Act and the Special Marriage Act?", answer: "The Hindu Marriage Act registers marriages already solemnised as per Hindu customs (also for Buddhists, Jains, Sikhs). The Special Marriage Act is used for civil and inter-faith marriages and involves a 30-day notice period." },
      { question: "How many witnesses are needed?", answer: "Usually two witnesses are required, each with valid identity and address proof. Some states may ask for three." },
      { question: "Can I apply for a marriage certificate online?", answer: "Many states allow you to start the application online through their e-District/marriage portal, but you may still need to visit the registrar's office in person for verification." },
    ],
    mistakes: [
      "Applying on an unofficial third-party website that charges extra",
      "Name/age mismatches between spouses' documents",
      "Not carrying original documents to the registrar for verification",
      "Choosing the wrong Act for your marriage type",
    ],
    relatedServices: ["birth-certificate", "aadhaar-card", "passport"],
    relatedBlog: ["how-to-apply-marriage-certificate-india"],
    relatedTools: ["image-compressor", "image-resizer", "pdf-merge", "pdf-compress"],
    keywords: ["marriage certificate", "marriage registration", "hindu marriage act", "special marriage act", "register marriage", "marriage certificate online"],
    popular: true,
    updatedOn: "2026-07-18",
  },
  {
    slug: "death-certificate",
    name: "Death Certificate",
    category: "certificates",
    officialName: "Civil Registration System (crsorgi.gov.in) / State portals",
    officialUrl: "https://crsorgi.gov.in",
    overview:
      "A death certificate is the official record of a death, issued by the Registrar of Births and Deaths through the Civil Registration System or your state/municipal portal. It is required to settle insurance claims, inheritance and property, close bank accounts, and claim pensions. Deaths should be registered within 21 days for free; later registration may need additional procedures.",
    documents: [
      "Proof of death (hospital/medical certificate of cause of death)",
      "Identity proof of the deceased (Aadhaar/other)",
      "Identity and address proof of the applicant",
      "Cremation/burial ground receipt (in some states)",
    ],
    eligibility: ["Family member/relative of the deceased", "Any person required to report the death as per law"],
    steps: [
      "Report the death to the local Registrar (hospital reports institutional deaths automatically in many states).",
      "Visit the Civil Registration System portal (crsorgi.gov.in) or your state/municipal portal.",
      "Fill the death-registration/certificate application.",
      "Upload the medical proof and applicant documents.",
      "Submit for verification and download/collect the certificate once issued.",
    ],
    fees: "Registration within 21 days is free. Late registration and additional copies may carry a small fee as per state rules.",
    processingTime: "Typically issued within a few days of verification; timelines vary by state.",
    validity: "A permanent legal record; it does not expire.",
    applyModes: ["Online (CRS / state portal)", "Offline (Municipal / Registrar office)"],
    faq: [
      { question: "Within how many days must a death be registered?", answer: "A death should be registered within 21 days for free. Registration after that is allowed but may require additional steps and a late fee." },
      { question: "Who can apply for a death certificate?", answer: "A close family member or relative of the deceased, or any person legally responsible for reporting the death." },
    ],
    mistakes: ["Delaying registration beyond 21 days", "Spelling mismatches with the deceased's records"],
    relatedServices: ["birth-certificate", "aadhaar-card"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["death certificate", "death registration", "crs death certificate", "how to get death certificate"],
    updatedOn: "2026-07-18",
  },
  {
    slug: "domicile-certificate",
    name: "Domicile / Residence Certificate",
    category: "certificates",
    officialName: "State Government e-District / Revenue portals",
    officialUrl: "https://services.india.gov.in",
    overview:
      "A domicile (residence) certificate proves that you are a permanent resident of a particular state. It is required for state quota admissions, government jobs, scholarships and other state benefits. It is issued by the State Government (Revenue/Tehsildar office) through the state's e-District portal.",
    documents: [
      "Proof of continuous residence in the state (as per state rule)",
      "Identity proof (Aadhaar/voter ID)",
      "Address proof",
      "Ration card / school records (in some states)",
      "Self-declaration / affidavit (as required)",
    ],
    eligibility: ["Permanent residents of the state, as per state-specific residence rules"],
    steps: [
      "Open your State's e-District/Revenue portal.",
      "Register and select 'Domicile / Residence Certificate'.",
      "Fill the form and upload residence and identity proofs.",
      "Submit to the Tehsildar/Revenue authority for verification.",
      "Download the digitally-signed certificate once issued.",
    ],
    fees: "A nominal fee applies and varies by state.",
    validity: "Often treated as long-term; some states may require renewal — check your state rules.",
    applyModes: ["Online (state e-District portal)", "Offline (Tehsil / Revenue office)"],
    faq: [
      { question: "What is a domicile certificate used for?", answer: "It proves permanent residence in a state and is used for state quota seats in colleges, state government jobs, scholarships and welfare benefits." },
      { question: "How long does it take?", answer: "Processing time varies by state, typically a few days to a couple of weeks after verification." },
    ],
    mistakes: ["Applying in the wrong state", "Insufficient proof of continuous residence"],
    relatedServices: ["income-certificate", "caste-certificate"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["domicile certificate", "residence certificate", "state resident proof", "domicile online"],
    updatedOn: "2026-07-18",
  },
  {
    slug: "disability-certificate",
    name: "Disability Certificate (UDID)",
    category: "certificates",
    officialName: "Department of Empowerment of Persons with Disabilities (UDID)",
    officialUrl: "https://www.swavlambancard.gov.in",
    overview:
      "The UDID (Unique Disability ID) project issues a disability certificate and a UDID card to persons with disabilities, giving a single document to access benefits and concessions. Apply online on the official Swavlamban/UDID portal; certification is done by a designated government medical authority.",
    documents: [
      "Recent passport-size photograph",
      "Identity proof (Aadhaar)",
      "Address proof",
      "Any existing disability certificate (if available)",
    ],
    eligibility: ["Persons with disabilities as defined under the Rights of Persons with Disabilities Act, 2016"],
    steps: [
      "Visit the official UDID portal (swavlambancard.gov.in).",
      "Register and fill the online application with personal details.",
      "Upload your photo and documents.",
      "Attend the assessment at the designated medical authority/hospital.",
      "Track your application and download the UDID card once the disability is certified.",
    ],
    fees: "There is no fee for the UDID application on the official portal.",
    applyModes: ["Online (UDID portal)", "Through the designated CMO/Medical Authority"],
    faq: [
      { question: "What is a UDID card?", answer: "It's a Unique Disability ID card issued under the UDID project that serves as a single, nationally-valid document of disability for availing benefits and concessions." },
      { question: "Is there a fee for the disability certificate?", answer: "No, the UDID application on the official portal is free." },
    ],
    mistakes: ["Using unofficial agents", "Missing the medical assessment appointment"],
    relatedServices: ["aadhaar-card"],
    relatedTools: ["image-compressor", "image-resizer", "pdf-compress"],
    keywords: ["disability certificate", "udid", "udid card", "handicap certificate", "swavlamban card", "divyang certificate"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- Utilities ---------------- */
  {
    slug: "ration-card",
    name: "Ration Card",
    category: "utilities",
    officialName: "State Food & Civil Supplies Departments",
    officialUrl: "https://nfsa.gov.in",
    overview:
      "A ration card lets eligible households buy subsidised food grains under the National Food Security Act (NFSA) and also serves as identity/address proof. Ration cards are issued by your State's Food & Civil Supplies Department; apply, add/remove members, or make corrections through your state's ration/PDS portal.",
    documents: [
      "Identity proof of the head of family (Aadhaar)",
      "Address proof",
      "Passport-size photograph of the head of family",
      "Details and Aadhaar of all family members",
      "Income proof (for category determination, as required)",
    ],
    eligibility: ["Households meeting the state's NFSA eligibility criteria", "One ration card per family"],
    steps: [
      "Find your State's Food & Civil Supplies / PDS portal (the NFSA site links to state portals).",
      "Register and select 'New Ration Card' (or update/correction).",
      "Fill the application with family and address details.",
      "Upload identity, address and member documents.",
      "Submit for verification by the local Food/Supply office.",
      "Track status and download/collect the ration card once approved.",
    ],
    fees: "A nominal fee (often ₹5–₹45) applies as per state; exact amounts are shown on the state portal.",
    validity: "Generally long-term; update it whenever family members or address change.",
    applyModes: ["Online (state PDS portal)", "Offline (Food & Supply / Ration office)"],
    faq: [
      { question: "How do I apply for a new ration card?", answer: "Apply on your State's Food & Civil Supplies/PDS portal with your family and address details and required documents. The NFSA portal (nfsa.gov.in) links to each state's portal." },
      { question: "Can I add a family member to my ration card?", answer: "Yes, use the 'add member' option on your state's ration portal with the new member's Aadhaar and proof." },
    ],
    mistakes: ["Holding more than one ration card", "Not linking all members' Aadhaar", "Applying on the wrong state portal"],
    relatedServices: ["aadhaar-card", "income-certificate", "electricity-bill-payment"],
    relatedBlog: ["how-to-get-new-ration-card-online"],
    relatedTools: ["image-compressor", "pdf-compress", "image-resizer"],
    keywords: ["ration card", "nfsa", "pds", "new ration card", "ration card apply", "food security card"],
    popular: true,
    updatedOn: "2026-07-18",
  },

  /* ---------------- Banking ---------------- */
  {
    slug: "jan-dhan-yojana",
    name: "Jan Dhan Account (PMJDY)",
    category: "banking",
    officialName: "Pradhan Mantri Jan Dhan Yojana",
    officialUrl: "https://pmjdy.gov.in",
    overview:
      "Pradhan Mantri Jan Dhan Yojana (PMJDY) provides basic, zero-balance savings accounts with benefits like a RuPay debit card, accident insurance cover and access to overdraft/Direct Benefit Transfer (DBT). You open a Jan Dhan account at any bank branch or Business Correspondent (Bank Mitra).",
    documents: ["Aadhaar (preferred)", "Any officially valid document (voter ID, driving licence, etc.) if Aadhaar isn't available", "Passport-size photograph"],
    eligibility: ["Any Indian citizen (including minors above 10 with a guardian)", "Should not already have a bank account (for a fresh account)"],
    steps: [
      "Read scheme details on the official PMJDY portal (pmjdy.gov.in).",
      "Visit any bank branch or a Bank Mitra (Business Correspondent).",
      "Fill the Jan Dhan account opening form.",
      "Submit Aadhaar/valid document and a photograph.",
      "Receive your zero-balance account and RuPay debit card.",
    ],
    fees: "Opening a Jan Dhan account is free and requires zero minimum balance.",
    applyModes: ["Offline (bank branch)", "Through a Bank Mitra / Business Correspondent"],
    faq: [
      { question: "Is a Jan Dhan account really zero balance?", answer: "Yes, PMJDY accounts can be opened and maintained with zero balance and come with a free RuPay debit card." },
      { question: "What benefits does a Jan Dhan account give?", answer: "A RuPay debit card, accident insurance cover, access to overdraft (subject to conditions) and receipt of government DBT benefits." },
    ],
    mistakes: ["Opening multiple accounts", "Not completing Aadhaar seeding for DBT"],
    relatedServices: ["aadhaar-card", "cibil-score", "sukanya-samriddhi-yojana"],
    relatedTools: ["emi-calculator", "percentage-calculator"],
    keywords: ["jan dhan", "pmjdy", "zero balance account", "jan dhan account", "rupay card"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- Agriculture ---------------- */
  {
    slug: "kisan-credit-card",
    name: "Kisan Credit Card (KCC)",
    category: "agriculture",
    officialName: "Kisan Credit Card Scheme (via banks)",
    officialUrl: "https://www.myscheme.gov.in/schemes/kcc",
    overview:
      "The Kisan Credit Card (KCC) gives farmers timely, affordable credit for cultivation and allied activities. Farmers apply through banks (many also allow applying via the PM-KISAN portal's KCC section) and receive a credit limit based on their landholding and crops.",
    documents: ["Identity proof (Aadhaar)", "Address proof", "Land ownership/records", "Passport-size photograph", "Bank account details"],
    eligibility: ["Farmers — individual/joint cultivators, tenant farmers, sharecroppers", "Members of SHGs/JLGs engaged in farming"],
    steps: [
      "Check scheme details on the official portal (myscheme.gov.in / your bank).",
      "Approach your bank branch or use the KCC option (e.g. via the PM-KISAN portal).",
      "Fill the KCC application with land and crop details.",
      "Submit identity, address and land documents.",
      "On approval, receive your KCC with the sanctioned credit limit.",
    ],
    applyModes: ["Offline (bank branch)", "Online (bank / PM-KISAN KCC section)"],
    faq: [
      { question: "Who is eligible for a Kisan Credit Card?", answer: "Farmers who own or cultivate land, including tenant farmers and sharecroppers, and eligible SHG/JLG members engaged in agriculture." },
      { question: "What can KCC be used for?", answer: "Short-term credit for crop cultivation, post-harvest expenses, and allied activities like dairy and fisheries, at concessional interest." },
    ],
    mistakes: ["Incomplete land records", "Applying without updated bank/Aadhaar linkage"],
    relatedServices: ["pm-kisan"],
    relatedTools: ["emi-calculator", "percentage-calculator"],
    keywords: ["kisan credit card", "kcc", "farmer loan", "agriculture credit", "kcc apply"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- Digital India ---------------- */
  {
    slug: "umang-app",
    name: "UMANG App",
    category: "digital-india",
    officialName: "UMANG (Unified Mobile Application for New-age Governance)",
    officialUrl: "https://web.umang.gov.in",
    overview:
      "UMANG is a single mobile/web app that provides access to thousands of central and state government services — from EPFO and PAN to gas booking, DigiLocker, Aadhaar and more — in one place. Register with your mobile number and access services without visiting multiple portals.",
    documents: ["Mobile number for registration", "Aadhaar (for certain services)"],
    eligibility: ["Any resident with a mobile number"],
    steps: [
      "Download the official UMANG app or visit web.umang.gov.in.",
      "Register with your mobile number and set an MPIN.",
      "Search for the government service you need.",
      "Complete the service-specific steps within UMANG.",
    ],
    fees: "UMANG is free to use.",
    applyModes: ["Mobile app", "Web (web.umang.gov.in)"],
    faq: [
      { question: "What services are on UMANG?", answer: "Thousands, including EPFO/PF, PAN, DigiLocker, Aadhaar, gas booking, pension, tax and many state services — all from one login." },
      { question: "Is UMANG official and safe?", answer: "Yes, UMANG is an official Government of India platform. Always download it from the official app store listing or web.umang.gov.in." },
    ],
    mistakes: ["Downloading look-alike apps", "Sharing your MPIN/OTP"],
    relatedServices: ["epfo", "digilocker", "aadhaar-card"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["umang", "umang app", "government app", "umang services", "epfo umang"],
    updatedOn: "2026-07-18",
  },
  {
    slug: "esic",
    name: "ESIC (Employees' State Insurance)",
    category: "employment",
    officialName: "Employees' State Insurance Corporation",
    officialUrl: "https://www.esic.gov.in",
    overview:
      "ESIC provides medical care and cash benefits to insured employees and their dependents under the Employees' State Insurance scheme. Employees registered by their employer get an ESIC (IP) number and can access ESI hospitals/dispensaries and benefits.",
    documents: ["Aadhaar", "Bank account details", "Family and nominee details", "Employer registration details"],
    eligibility: ["Employees in covered establishments earning up to the notified wage limit"],
    steps: [
      "Employer registers the establishment and employees on the ESIC portal (esic.gov.in).",
      "Employee receives an Insurance Number (IP number) and e-Pehchan/ESI card.",
      "Register family details for dependent benefits.",
      "Avail medical care at ESI hospitals/dispensaries and cash benefits as applicable.",
    ],
    faq: [
      { question: "Who is covered under ESIC?", answer: "Employees in covered establishments earning within the notified wage ceiling are covered, along with their dependents." },
      { question: "How do I get my ESIC number?", answer: "Your employer registers you on the ESIC portal, after which you get an Insurance (IP) number and ESI card." },
    ],
    mistakes: ["Incomplete family/nominee details", "Not carrying the ESI card to the dispensary"],
    relatedServices: ["epfo"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["esic", "employees state insurance", "esi card", "esic number", "esi benefits"],
    updatedOn: "2026-07-18",
  },

  /* ---------------- High-traffic additions ---------------- */
  {
    slug: "pan-aadhaar-link",
    name: "PAN–Aadhaar Link & Status",
    category: "identity-documents",
    officialName: "Income Tax Department",
    officialUrl: "https://www.incometax.gov.in",
    overview:
      "Linking your PAN with Aadhaar is mandatory for most taxpayers. An unlinked PAN can become inoperative, which blocks ITR filing, refunds and many financial transactions. You can link PAN with Aadhaar and check the link status directly on the official Income Tax e-filing portal.",
    documents: ["PAN number", "Aadhaar number", "Mobile number for OTP"],
    eligibility: ["PAN holders required to link under the Income Tax rules (with limited exemptions such as certain non-residents, super senior citizens and specified states)"],
    steps: [
      "Go to the official Income Tax e-filing portal (incometax.gov.in).",
      "On the home page, open 'Link Aadhaar' under Quick Links.",
      "Enter your PAN and Aadhaar number.",
      "If a late fee applies, pay it first (via e-Pay Tax) and then submit the link request.",
      "Use 'Link Aadhaar Status' to confirm the linking is complete.",
    ],
    fees: "A late fee applies for linking after the notified deadline; the current amount is shown on the portal during payment.",
    processingTime: "Status usually updates within a few days of a successful request.",
    applyModes: ["Online (Income Tax portal)", "SMS to the notified number (as published)"],
    officialLinks: [
      { label: "Link Aadhaar Status", url: "https://www.incometax.gov.in/iec/foportal/help/individual/link-aadhaar-status" },
    ],
    faq: [
      { question: "How do I check if my PAN and Aadhaar are linked?", answer: "Use the 'Link Aadhaar Status' option on incometax.gov.in and enter your PAN and Aadhaar — it shows whether they're already linked." },
      { question: "What happens if PAN is not linked to Aadhaar?", answer: "The PAN can become inoperative, which can stop you from filing ITR, getting refunds, and carrying out several high-value financial transactions." },
    ],
    mistakes: ["Name/DOB mismatch between PAN and Aadhaar", "Not paying the late fee before submitting the link request", "Using unofficial sites that charge extra"],
    relatedServices: ["pan-card", "aadhaar-card", "itr-filing"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["pan aadhaar link", "link pan with aadhaar", "pan aadhaar status", "pan inoperative", "aadhaar pan linking"],
    popular: true,
    updatedOn: "2026-07-19",
  },
  {
    slug: "e-challan",
    name: "Traffic e-Challan (Check & Pay)",
    category: "vehicles",
    officialName: "eChallan, Parivahan (Ministry of Road Transport & Highways)",
    officialUrl: "https://echallan.parivahan.gov.in",
    overview:
      "The eChallan portal lets you check and pay traffic-violation challans issued against your vehicle or driving licence. Enter your vehicle number, challan number or DL to view pending challans and pay them online.",
    documents: ["Vehicle registration (RC) number, or challan number, or driving licence number", "Mobile number for OTP"],
    eligibility: ["Any vehicle owner / driver with an issued challan"],
    steps: [
      "Visit the official eChallan portal (echallan.parivahan.gov.in).",
      "Choose 'Check Challan Status'.",
      "Enter your vehicle number / challan number / DL number and verify via OTP.",
      "Review the pending challan details.",
      "Pay online and save the payment receipt.",
    ],
    applyModes: ["Online (eChallan portal)", "Online (state traffic police portals)", "Offline (traffic police / court)"],
    officialLinks: [
      { label: "Check Challan Status", url: "https://echallan.parivahan.gov.in/index/accused-challan" },
    ],
    faq: [
      { question: "How do I check my traffic challan online?", answer: "Go to echallan.parivahan.gov.in, choose 'Check Challan Status', and enter your vehicle number, challan number or driving licence number." },
      { question: "Can I pay a traffic challan online?", answer: "Yes, pending challans can be paid online on the eChallan portal or your state traffic police portal, and you get a digital receipt." },
    ],
    mistakes: ["Paying on unofficial look-alike sites", "Ignoring challans until they escalate to court", "Entering the wrong vehicle/DL number"],
    relatedServices: ["vehicle-rc", "driving-licence"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["e challan", "echallan", "traffic challan", "check challan", "pay challan online", "parivahan challan"],
    popular: true,
    updatedOn: "2026-07-19",
  },
  {
    slug: "fastag",
    name: "FASTag",
    category: "vehicles",
    officialName: "NPCI / NHAI (issuing banks)",
    officialUrl: "https://www.npci.org.in/what-we-do/netc-fastag/product-overview",
    overview:
      "FASTag is a reloadable tag that enables automatic electronic toll payment at highway toll plazas using RFID. FASTags are issued by member banks and can be bought, recharged and managed online or at points of sale.",
    documents: ["Vehicle Registration Certificate (RC)", "Identity and address proof (KYC)", "Passport-size photograph", "Vehicle owner's KYC per the issuing bank"],
    eligibility: ["Owners of four-wheelers and other eligible vehicles"],
    steps: [
      "Choose an authorised issuing bank / provider (list available via NPCI/NHAI).",
      "Buy FASTag online or at a bank branch / toll plaza / point of sale.",
      "Submit RC and KYC documents.",
      "Affix the tag on your windscreen as instructed.",
      "Recharge the linked wallet/account to pay tolls automatically.",
    ],
    applyModes: ["Online (issuing bank / provider)", "Offline (bank branch, toll plaza, PoS)"],
    faq: [
      { question: "Is FASTag mandatory?", answer: "FASTag is mandatory for toll payment at National Highway plazas; vehicles without a valid FASTag can be charged a higher toll." },
      { question: "How do I recharge FASTag?", answer: "Recharge through your issuing bank's app/website, UPI, or the NETC/UMANG channels linked to your FASTag account." },
    ],
    mistakes: ["Buying from unauthorised sellers", "Not completing KYC (tag gets limited)", "Low balance causing toll-lane issues"],
    relatedServices: ["vehicle-rc", "e-challan"],
    relatedTools: ["image-compressor", "pdf-compress"],
    keywords: ["fastag", "fastag recharge", "netc fastag", "toll tag", "apply fastag", "fastag kyc"],
    updatedOn: "2026-07-19",
  },
  {
    slug: "cibil-score",
    name: "Credit Score (CIBIL) Check",
    category: "banking",
    officialName: "RBI-licensed Credit Information Companies (CICs)",
    officialUrl: "https://www.rbi.org.in",
    overview:
      "Your credit score (often called CIBIL score) reflects your creditworthiness based on your loan and card repayment history. Under RBI rules, each of the four licensed Credit Information Companies must give you one free full credit report a year. Check your score directly on the official CIC websites — you don't need any paid third-party 'score checker'.",
    documents: ["PAN", "Identity/contact details for verification"],
    eligibility: ["Anyone with a credit history (loans/credit cards) in India"],
    steps: [
      "Go to an RBI-licensed Credit Information Company's official website (CIBIL/Experian/Equifax/CRIF High Mark).",
      "Register with your PAN and personal details.",
      "Verify your identity via OTP.",
      "View your credit score and full credit report.",
      "Use your one free annual full report from each CIC to review for errors.",
    ],
    fees: "You are entitled to one free full credit report per year from each licensed CIC. Frequent/real-time score services may be paid.",
    applyModes: ["Online (official CIC websites)"],
    faq: [
      { question: "How can I check my CIBIL score for free?", answer: "Every RBI-licensed credit bureau must provide one free full credit report a year. Register on the official bureau website with your PAN to view your score and report — avoid paid third-party 'checkers'." },
      { question: "What is a good credit score?", answer: "Scores range roughly 300–900; a higher score (commonly 750+) generally improves your chances of loan and card approval on better terms." },
    ],
    mistakes: ["Sharing card/bank OTPs with 'score checker' apps", "Assuming one bureau's score is the only one", "Ignoring errors in the report instead of raising a dispute"],
    relatedServices: ["jan-dhan-yojana"],
    relatedTools: ["emi-calculator", "percentage-calculator"],
    keywords: ["cibil score", "credit score", "check cibil", "free credit report", "credit bureau", "cibil check"],
    popular: true,
    updatedOn: "2026-07-19",
  },
  {
    slug: "ews-certificate",
    name: "EWS Certificate",
    category: "certificates",
    officialName: "State Government e-District / Revenue portals",
    officialUrl: "https://services.india.gov.in",
    overview:
      "An EWS (Economically Weaker Section) certificate — also called an Income & Asset certificate — lets eligible general-category applicants claim the 10% EWS reservation in education and government jobs. It is issued by the State Government (Revenue authority) through the state's e-District portal, based on family income and asset limits.",
    documents: [
      "Identity proof (Aadhaar)",
      "Address proof",
      "Income proof of the family (as per the EWS limit)",
      "Land/asset details / self-declaration",
      "Ration card / other documents (as per state)",
    ],
    eligibility: ["General-category families within the notified EWS income and asset limits (not covered by SC/ST/OBC reservation)"],
    steps: [
      "Open your State's e-District/Revenue portal.",
      "Register and select 'EWS' / 'Income & Asset Certificate'.",
      "Fill the family income and asset details.",
      "Upload the required proofs.",
      "Submit for verification by the Revenue authority (Tehsildar/SDM).",
      "Download the digitally-signed certificate once issued.",
    ],
    fees: "A nominal fee applies and varies by state.",
    validity: "EWS certificates are typically valid for one financial year and are renewed annually.",
    applyModes: ["Online (state e-District portal)", "Offline (Tehsil / Revenue office)"],
    faq: [
      { question: "Who can get an EWS certificate?", answer: "General-category families (not covered by SC/ST/OBC reservation) whose income and assets are within the notified EWS limits." },
      { question: "How long is an EWS certificate valid?", answer: "It is generally valid for one financial year and must be renewed for continued use." },
    ],
    mistakes: ["Declaring income above the EWS limit", "Applying while eligible under another reserved category", "Wrong state portal"],
    relatedServices: ["income-certificate", "caste-certificate", "domicile-certificate"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["ews certificate", "economically weaker section", "income and asset certificate", "ews reservation", "10% ews"],
    updatedOn: "2026-07-19",
  },
  {
    slug: "police-clearance-certificate",
    name: "Police Clearance Certificate (PCC)",
    category: "travel-immigration",
    officialName: "Passport Seva, Ministry of External Affairs",
    officialUrl: "https://www.passportindia.gov.in",
    overview:
      "A Police Clearance Certificate (PCC) certifies that you have no criminal record, and is commonly required for long-term visas, residency, overseas employment and immigration. For Indian passport holders, PCC is applied through Passport Seva and issued after police verification.",
    documents: ["Valid passport", "Proof of present address", "Purpose/visa details (e.g. employment, residency)", "Additional documents as required for the destination country"],
    eligibility: ["Indian passport holders needing a PCC (e.g. for visa, immigration or overseas jobs)"],
    steps: [
      "Register/sign in on the Passport Seva portal (passportindia.gov.in).",
      "Select 'Apply for Police Clearance Certificate (PCC)'.",
      "Fill the application and pay the fee.",
      "Book an appointment at a PSK/POPSK.",
      "Visit for verification; PCC is issued after police verification (where required).",
    ],
    fees: "The PCC fee is shown on the Passport Seva portal during payment.",
    processingTime: "Depends on whether police verification is required for your case.",
    applyModes: ["Online application via Passport Seva", "In-person verification at PSK/POPSK"],
    faq: [
      { question: "Who needs a Police Clearance Certificate?", answer: "People applying for long-term visas, residency, immigration or overseas employment are commonly asked to submit a PCC." },
      { question: "How do I apply for a PCC in India?", answer: "Apply through the Passport Seva portal, pay the fee, book a PSK appointment, and complete verification. PCC is issued after any required police verification." },
    ],
    mistakes: ["Address mismatch causing longer verification", "Not carrying original passport to the PSK", "Applying at the wrong PSK jurisdiction"],
    relatedServices: ["passport", "aadhaar-card"],
    relatedTools: ["image-compressor-for-passport-photo", "image-compressor", "pdf-compress"],
    keywords: ["police clearance certificate", "pcc", "pcc passport", "police verification certificate", "pcc for visa"],
    updatedOn: "2026-07-19",
  },
  {
    slug: "electricity-bill-payment",
    name: "Electricity Bill Payment",
    category: "utilities",
    officialName: "State Electricity Boards / DISCOMs",
    officialUrl: "https://www.bharatbillpay.com",
    overview:
      "You can view and pay your electricity bill online through your State Electricity Board / DISCOM website or via the Bharat BillPay (BBPS) system available across many apps and banks. Enter your consumer/account number to fetch and pay the current bill.",
    documents: ["Electricity consumer number / account number (from your bill)", "Registered mobile number"],
    eligibility: ["Any electricity consumer with an active connection"],
    steps: [
      "Open your State Electricity Board / DISCOM portal, or a BBPS-enabled app/bank.",
      "Select 'Electricity' and your board/DISCOM.",
      "Enter your consumer/account number.",
      "View the current bill amount and details.",
      "Pay online and save the digital receipt.",
    ],
    applyModes: ["Online (DISCOM portal)", "BBPS / bank apps", "Offline (bill collection centres)"],
    faq: [
      { question: "How do I pay my electricity bill online?", answer: "Use your DISCOM's official portal or any BBPS-enabled app/bank, enter your consumer number to fetch the bill, and pay online." },
      { question: "Where do I find my consumer number?", answer: "It's printed on your electricity bill, usually near your name and connection details." },
    ],
    mistakes: ["Entering the wrong consumer number", "Using unofficial payment links", "Not saving the payment receipt"],
    relatedServices: ["ration-card"],
    relatedTools: ["pdf-compress", "image-compressor"],
    keywords: ["electricity bill", "pay electricity bill online", "bijli bill", "bbps electricity", "discom bill payment"],
    updatedOn: "2026-07-19",
  },
  {
    slug: "sukanya-samriddhi-yojana",
    name: "Sukanya Samriddhi Yojana (SSY)",
    category: "banking",
    officialName: "Department of Posts / Ministry of Finance",
    officialUrl: "https://www.indiapost.gov.in",
    overview:
      "Sukanya Samriddhi Yojana (SSY) is a government small-savings scheme for a girl child, offering an attractive fixed interest rate and tax benefits. A parent/guardian opens the account at a Post Office or authorised bank and deposits annually until the girl reaches the notified age.",
    documents: [
      "Birth certificate of the girl child",
      "Identity and address proof of the parent/guardian",
      "Passport-size photographs",
      "Account opening form (from Post Office / bank)",
    ],
    eligibility: ["A girl child below 10 years of age", "Opened and operated by a parent/legal guardian", "Up to two accounts per family (with specified exceptions for twins/triplets)"],
    steps: [
      "Visit a Post Office or an authorised bank branch.",
      "Collect and fill the SSY account opening form.",
      "Submit the girl child's birth certificate and guardian's KYC.",
      "Make the initial deposit to open the account.",
      "Continue annual deposits within the notified minimum/maximum limits.",
    ],
    fees: "No account-opening fee; deposits are as per the scheme's minimum and maximum limits.",
    applyModes: ["Offline (Post Office / authorised bank)", "Some banks offer online deposits after opening"],
    faq: [
      { question: "Who can open a Sukanya Samriddhi account?", answer: "A parent or legal guardian can open it for a girl child below 10 years of age, at a Post Office or authorised bank." },
      { question: "What are the tax benefits of SSY?", answer: "SSY enjoys EEE tax treatment — deposits qualify for deduction under Section 80C, and the interest and maturity amount are tax-free, subject to prevailing rules." },
    ],
    mistakes: ["Missing the minimum annual deposit (account can go dormant)", "Opening more accounts than allowed", "Losing the passbook without recording deposits"],
    relatedServices: ["jan-dhan-yojana", "birth-certificate"],
    relatedTools: ["emi-calculator", "percentage-calculator"],
    keywords: ["sukanya samriddhi", "ssy", "girl child scheme", "sukanya samriddhi yojana", "ssy account", "post office ssy"],
    updatedOn: "2026-07-19",
  },
];

/* ---------------- helpers ---------------- */
export function getIndiaService(slug: string): IndiaService | undefined {
  return indiaServices.find((s) => s.slug === slug);
}
export function servicesByCategory(category: string): IndiaService[] {
  return indiaServices.filter((s) => s.category === category);
}
export function popularIndiaServices(): IndiaService[] {
  const p = indiaServices.filter((s) => s.popular);
  return p.length ? p : indiaServices.slice(0, 8);
}
export function relatedIndiaServices(service: IndiaService, limit = 4): IndiaService[] {
  const explicit = (service.relatedServices ?? []).map(getIndiaService).filter((s): s is IndiaService => !!s);
  const sameCat = servicesByCategory(service.category).filter((s) => s.slug !== service.slug);
  const seen = new Set<string>();
  return [...explicit, ...sameCat].filter((s) => (seen.has(s.slug) ? false : (seen.add(s.slug), true))).slice(0, limit);
}

/* Intent-aware search over services (problems, questions, use cases). */
const INDIA_INTENTS: { keys: string[]; slug: string }[] = [
  { keys: ["lost aadhaar", "aadhaar lost", "forgot aadhaar", "aadhaar number", "download aadhaar", "aadhaar address"], slug: "aadhaar-card" },
  { keys: ["need pan", "apply pan", "lost pan", "e-pan", "pan correction"], slug: "pan-card" },
  { keys: ["need passport", "apply passport", "passport renewal", "passport photo"], slug: "passport" },
  { keys: ["driving licence renewal", "learner licence", "apply dl", "driving license"], slug: "driving-licence" },
  { keys: ["rc transfer", "vehicle registration", "duplicate rc", "ownership transfer"], slug: "vehicle-rc" },
  { keys: ["income certificate"], slug: "income-certificate" },
  { keys: ["caste certificate", "community certificate", "obc certificate", "sc st certificate"], slug: "caste-certificate" },
  { keys: ["birth certificate", "birth registration"], slug: "birth-certificate" },
  { keys: ["gst registration", "gst number", "register gst", "gstin"], slug: "gst-registration" },
  { keys: ["msme", "udyam", "small business registration"], slug: "msme-udyam" },
  { keys: ["itr", "income tax return", "file tax"], slug: "itr-filing" },
  { keys: ["abha", "health id", "abdm"], slug: "abha-health-id" },
  { keys: ["ayushman", "pmjay", "health card", "golden card"], slug: "ayushman-bharat" },
  { keys: ["pf", "epfo", "provident fund", "pf balance", "pf withdrawal", "uan"], slug: "epfo" },
  { keys: ["eshram", "e-shram", "labour card", "unorganised worker"], slug: "eshram" },
  { keys: ["scholarship", "nsp", "student scholarship"], slug: "scholarship" },
  { keys: ["pm kisan", "kisan", "farmer scheme"], slug: "pm-kisan" },
  { keys: ["digilocker", "digital documents"], slug: "digilocker" },
  { keys: ["voter id", "voter registration", "epic"], slug: "voter-id" },
  { keys: ["marriage certificate", "register marriage", "marriage registration", "shaadi certificate"], slug: "marriage-certificate" },
  { keys: ["death certificate", "death registration"], slug: "death-certificate" },
  { keys: ["domicile", "residence certificate", "resident proof"], slug: "domicile-certificate" },
  { keys: ["disability certificate", "udid", "handicap certificate", "divyang"], slug: "disability-certificate" },
  { keys: ["ration card", "new ration card", "pds", "food card"], slug: "ration-card" },
  { keys: ["jan dhan", "zero balance account", "pmjdy"], slug: "jan-dhan-yojana" },
  { keys: ["kisan credit card", "kcc", "farmer loan"], slug: "kisan-credit-card" },
  { keys: ["umang", "government app"], slug: "umang-app" },
  { keys: ["esic", "esi card", "employee insurance"], slug: "esic" },
  { keys: ["pan aadhaar link", "link pan aadhaar", "link aadhaar", "pan aadhaar status", "pan inoperative"], slug: "pan-aadhaar-link" },
  { keys: ["e challan", "echallan", "traffic challan", "check challan", "pay challan"], slug: "e-challan" },
  { keys: ["fastag", "fas tag", "toll tag", "netc"], slug: "fastag" },
  { keys: ["cibil", "credit score", "credit report", "cibil score"], slug: "cibil-score" },
  { keys: ["ews certificate", "economically weaker section", "income and asset certificate", "ews reservation"], slug: "ews-certificate" },
  { keys: ["police clearance", "pcc", "police verification certificate"], slug: "police-clearance-certificate" },
  { keys: ["electricity bill", "bijli bill", "pay electricity", "discom bill"], slug: "electricity-bill-payment" },
  { keys: ["sukanya", "ssy", "girl child scheme", "sukanya samriddhi"], slug: "sukanya-samriddhi-yojana" },
];

export interface IndiaSearchResult {
  slug: string;
  name: string;
  category: string;
}

export function searchIndiaServices(query: string, limit = 8): IndiaSearchResult[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const seen = new Set<string>();
  const out: IndiaSearchResult[] = [];
  const add = (svc?: IndiaService) => {
    if (svc && !seen.has(svc.slug)) { seen.add(svc.slug); out.push({ slug: svc.slug, name: svc.name, category: svc.category }); }
  };
  for (const intent of INDIA_INTENTS) {
    if (intent.keys.some((k) => q.includes(k) || k.includes(q))) add(getIndiaService(intent.slug));
    if (out.length >= limit) break;
  }
  if (out.length < limit) {
    for (const s of indiaServices) {
      const hay = `${s.name} ${s.keywords.join(" ")} ${s.officialName}`.toLowerCase();
      if (hay.includes(q)) add(s);
      if (out.length >= limit) break;
    }
  }
  return out.slice(0, limit);
}
