"use client";

import { useMemo, useRef, useState, type ChangeEvent } from "react";
import { Upload } from "lucide-react";
import { useCopy } from "@/hooks/use-copy";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { ActionBar } from "@/components/tools/action-bar";
import { downloadBlob } from "@/lib/utils";

const SAMPLE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120" viewBox="0 0 120 120">
  <!-- generated by design tool -->
  <circle cx="60.0000" cy="60.0000" r="45.5000" fill="#6366f1" />
</svg>`;

function formatBytes(b: number) {
  if (b < 1048576) return `${(b / 1024).toFixed(1)} KB`;
  return `${(b / 1048576).toFixed(2)} MB`;
}

function byteLength(s: string) {
  return new TextEncoder().encode(s).length;
}

/**
 * Hand-rolled SVG optimizer (no SVGO dependency). Applies a sequence of
 * safe, regex-based cleanups: strip comments/doctype, drop editor cruft,
 * collapse whitespace, and round numeric precision.
 */
function optimizeSvg(source: string, removeTitleDesc: boolean): string {
  let out = source;

  // 1. Remove XML comments.
  out = out.replace(/<!--[\s\S]*?-->/g, "");

  // 2. Remove the XML declaration and any DOCTYPE.
  out = out.replace(/<\?xml[\s\S]*?\?>/gi, "");
  out = out.replace(/<!DOCTYPE[\s\S]*?>/gi, "");

  // 3. Editor metadata cleanup.
  if (removeTitleDesc) {
    out = out.replace(/<title[^>]*>[\s\S]*?<\/title>/gi, "");
    out = out.replace(/<desc[^>]*>[\s\S]*?<\/desc>/gi, "");
  }
  // Illustrator/Sketch/Figma export cruft attributes.
  out = out.replace(/\s+data-name="[^"]*"/gi, "");
  out = out.replace(/\s+data-name='[^']*'/gi, "");

  // Drop xmlns:xlink only if no xlink: attribute is actually used.
  const withoutXlinkDecl = out.replace(/\s+xmlns:xlink="[^"]*"/gi, "");
  const usesXlink = /\bxlink:[a-zA-Z-]+\s*=/.test(withoutXlinkDecl);
  if (!usesXlink) {
    out = out.replace(/\s+xmlns:xlink="[^"]*"/gi, "");
  }

  // Empty <defs></defs> / <g></g> groups with no attributes and no children.
  out = out.replace(/<defs>\s*<\/defs>/gi, "");
  out = out.replace(/<g>\s*<\/g>/gi, "");

  // 4. Collapse redundant whitespace.
  out = out.replace(/[\t\n\r]+/g, " ");
  out = out.replace(/\s{2,}/g, " ");
  out = out.replace(/>\s+</g, "><");
  out = out.trim();

  // 5. Round floating point numbers to 2 decimal places.
  out = out.replace(/-?\d+\.\d+/g, (match) => {
    const rounded = Math.round(parseFloat(match) * 100) / 100;
    return String(rounded);
  });

  // 6. xmlns="http://www.w3.org/2000/svg" is intentionally kept (required
  // for a standalone SVG document); only the unused xlink namespace above
  // is stripped.

  return out;
}

export default function SvgOptimizer() {
  const [input, setInput] = useState(SAMPLE_SVG);
  const [removeTitleDesc, setRemoveTitleDesc] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { copied, copy } = useCopy();

  const output = useMemo(() => (input.trim() ? optimizeSvg(input, removeTitleDesc) : ""), [input, removeTitleDesc]);

  const originalBytes = useMemo(() => byteLength(input), [input]);
  const optimizedBytes = useMemo(() => byteLength(output), [output]);
  const reduction = originalBytes > 0 ? Math.max(0, Math.round(((originalBytes - optimizedBytes) / originalBytes) * 1000) / 10) : 0;

  const handleFile = async (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const text = await file.text();
    setInput(text);
    e.target.value = "";
  };

  return (
    <div className="grid gap-6 lg:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle>Original</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="svg-input">Paste SVG markup</Label>
            <Textarea
              id="svg-input"
              className="min-h-[220px] font-mono text-xs"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Paste SVG markup here…"
            />
          </div>

          <input
            ref={fileInputRef}
            id="svg-file-upload"
            type="file"
            accept=".svg,image/svg+xml"
            className="hidden"
            onChange={handleFile}
          />
          <Label htmlFor="svg-file-upload" className="sr-only">
            Upload SVG file
          </Label>
          <Button type="button" variant="outline" className="w-full" onClick={() => fileInputRef.current?.click()}>
            <Upload className="size-4" /> Upload SVG file
          </Button>

          {input.trim() && (
            <div className="space-y-1.5">
              <Label htmlFor="svg-original-preview">Preview</Label>
              <div
                id="svg-original-preview"
                className="flex h-40 items-center justify-center overflow-hidden rounded-xl border border-border bg-secondary/30 p-3 [&_svg]:max-h-full [&_svg]:max-w-full"
                dangerouslySetInnerHTML={{ __html: input }}
              />
              <p className="text-xs text-muted-foreground">Size: {formatBytes(originalBytes)}</p>
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Optimized</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <label className="flex cursor-pointer items-center justify-between rounded-xl border border-border p-3 text-sm">
            Remove &lt;title&gt;/&lt;desc&gt; tags
            <input
              type="checkbox"
              checked={removeTitleDesc}
              onChange={(e) => setRemoveTitleDesc(e.target.checked)}
              className="size-4 accent-[hsl(var(--primary))]"
            />
          </label>

          <div className="space-y-1.5">
            <Label htmlFor="svg-output">Optimized markup</Label>
            <Textarea id="svg-output" readOnly className="min-h-[220px] font-mono text-xs" value={output} placeholder="Optimized SVG appears here…" />
          </div>

          {output && (
            <ActionBar
              onCopy={() => copy(output)}
              copied={copied}
              onDownload={() => downloadBlob(new Blob([output], { type: "image/svg+xml" }), "optimized.svg")}
              downloadLabel="Download"
            />
          )}

          {output && (
            <div className="space-y-1.5">
              <Label htmlFor="svg-optimized-preview">Preview</Label>
              <div
                id="svg-optimized-preview"
                className="flex h-40 items-center justify-center overflow-hidden rounded-xl border border-border bg-secondary/30 p-3 [&_svg]:max-h-full [&_svg]:max-w-full"
                dangerouslySetInnerHTML={{ __html: output }}
              />
              <p className="text-xs text-muted-foreground">Size: {formatBytes(optimizedBytes)}</p>
            </div>
          )}

          {output && (
            <div className="rounded-xl bg-secondary/50 p-3 text-sm">
              <span className="font-medium">{formatBytes(originalBytes)}</span>
              <span className="text-muted-foreground"> → </span>
              <span className="font-medium">{formatBytes(optimizedBytes)}</span>
              <span className="ml-2 text-emerald-500 font-semibold">-{reduction}%</span>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
